### ISSUE TITLE
Speed and fluidity of the animation

### ISSUE THREAD

**Issue by matiux** [darioielardi/flutter_speed_dial#1]
Hi,
is there a way to adjust the fluidity of the opening and closing animation of the menu?
It seems to me that it goes a little slow. Almost as if it were snapping.

**Comment by darioielardi** [comment]
It could be just an additional parameter, I'll work on it soon but you could just submit a PR :)

**Comment by TECHNOFAB11** [comment]
Got the same 'issue'. For me it feels very snappy and not fluid if compared to the Google Calendar app where it's really smooth for example. Tried playing around with the curves, but still not smooth

**Comment by marcjoha** [comment]
@TECHNOFAB11 the above pull request introduced an `animationSpeed` parameter you can tune.

**Comment by prateekmedia** [comment]
Try `animationSpeed` property.
