### ISSUE TITLE
The method 'stop' was called on null

### ISSUE THREAD

**Issue by Stnieder** [darioielardi/flutter_speed_dial#10]
All working great, only this error is showing up in the console:

>     animation_controller.dart in AnimationController.stop at line 650
>     animation_controller.dart in AnimationController._animateToInternal at line 525
>     animation_controller.dart in AnimationController.reverse at line 470
>     speed_dial.dart in _SpeedDialState._performAnimation.<fn>.<fn> at line 127
>     zone.dart in _rootRun at line 1120
>     zone.dart in _CustomZone.run at line 1021
>     zone.dart in _CustomZone.runGuarded at line 923
>     zone.dart in _CustomZone.bindCallbackGuarded.<fn> at line 963
>     zone.dart in _rootRun at line 1124
>     zone.dart in _CustomZone.run at line 1021
>     zone.dart in _CustomZone.bindCallback.<fn> at line 947
>     libtimer_patch.dart in Timer._createTimer.<fn> at line 21
>     libtimer_impl.dart in _Timer._runTimers at line 382
>     libtimer_impl.dart in _Timer._handleMessage at line 416
>     libisolate_patch.dart in _RawReceivePortImpl._handleMessage at line 171

After clicking on the speed_dial button the error shows up.

**Comment by Stnieder** [comment]
I get this only as Error Message in Release mode. And then only as a report of **sentry.io**

**Comment by anderscheow** [comment]
I think this can be reproduce when the SpeedDial is dismissing while the page is pop or closed

**Comment by zanecidan** [comment]
I am also getting this issue once in a while. When it happened the speed dial child would go haywire (showing incorrectly).

**Comment by darioielardi** [comment]
I noticed something similar once, I'll try to reproduce that.

**Comment by kinex** [comment]
Same issue here. I think the bug is caused by referencing an AnimationController which may have already been disposed e.g. here https://github.com/darioielardi/flutter_speed_dial/blob/master/lib/src/speed_dial.dart#L123

In Timer callback you should check if this object has already been disposed. Something like this:
        
```dart
Timer(
  Duration(milliseconds: index * 40),
  () { 
    if (!_disposed) {
      childController.forward() 
    },
  }
);
```

**Comment by anderscheow** [comment]
@darioielardi Would it be great to use `if (mounted)` before executing animation controller inside the Timer?
