### ISSUE TITLE
[BUG] Child button are not aligned

### ISSUE THREAD

**Issue by enricobenedos** [darioielardi/flutter_speed_dial#103]
I'm switching from `flutter_speed_dial 1.2.5` to `flutter_speed_dial 2.1.1` and child buttons are not aligned correctly. 
The code is the same and I'm not using margin/paddings.

* `flutter_speed_dial 1.2.5` vs `flutter_speed_dial 2.2.1`

![image](https://user-images.githubusercontent.com/12233746/108249582-89069180-7155-11eb-8513-ae012da91906.png) ![image](https://user-images.githubusercontent.com/12233746/108249616-915ecc80-7155-11eb-8c07-44f897334827.png)

**Comment by prateekmedia** [comment]
Could you test it now please, but from this git repository.

**Comment by enricobenedos** [comment]
I think it is already not aligned

![image](https://user-images.githubusercontent.com/12233746/109055022-f29b1880-76de-11eb-8105-556842b1d7cc.png)

**Comment by lks-nbg** [comment]
@prateekmedia i think i found a solution for this issue

[animated_floating_button.dart](https://github.com/darioielardi/flutter_speed_dial/blob/master/lib/src/animated_floating_button.dart):
I added `width: size,` in line 48 to make sure that the there is no empty space on the left or right of the main Button.

[speed_dial.dart](https://github.com/darioielardi/flutter_speed_dial/blob/master/lib/src/speed_dial.dart) 
and in line 414 & 432 i removed the margin `end: 2.0` which i believe is the reason for the disalignment.

For me these adjustments solved the issue. Would be great if someone else could try and approve this.

**Comment by prateekmedia** [comment]
@lks-nbg Firstly thank you very much. 

Secondly, 
> animated_floating_button.dart:
> I added width: size, in line 48 to make sure that the there is no empty space on the left or right of the main Button.

This is not needed, as the scope of the speed dial is now also to provide an extended floating button which has a width far greater than buttonSize, your this code will try to produce renderOverflow when running with respect to that.

**Comment by prateekmedia** [comment]
@enricobenedos Can you test the linked PR please, I think it should fix it,

```
  flutter_speed_dial:
    git:
      url: git://github.com/darioielardi/flutter_speed_dial.git
      ref: prateekmedia-patch-103
```
