### ISSUE TITLE
ButtonChild is not visible if buttonSize <= 50.0

### ISSUE THREAD

**Issue by lks-nbg** [darioielardi/flutter_speed_dial#112]
The AnimatedChild currently only shows the ButtonChild if the size is larger than 50.0. This makes sense when the default buttonSize of 56.0 is used (approx. 90%). With a buttonSize <= 50.0 the condition will never be true, so the child will never be visible (see screenshot below).

I recommend replacing the hard coded value of 50.0 with "(buttonSize * 0.9)" or something similar.
 
[animated_child.dart (Line 111)](https://github.com/darioielardi/flutter_speed_dial/blob/master/lib/src/animated_child.dart) 
`final Widget buttonChild = animation.value > 50.0 && child !=null
        ? Container(
            width: animation.value,
            height: animation.value,
            child: child,
          )
        : Container(
            width: 0.0,
            height: 0.0,
          );`

![screenshot](https://user-images.githubusercontent.com/42645195/109987863-47561900-7d07-11eb-86c0-a2d108877dbc.png)

**Comment by prateekmedia** [comment]
You can try it now, thanks btw.

Also do you know why the alignment is disturbed in the new version of flutter speed dial? I can't find the core issue.

**Comment by lks-nbg** [comment]
Thanks for the quick implementation! I think I found the reason for the disalignment and commented on the issue --> https://github.com/darioielardi/flutter_speed_dial/issues/103#issuecomment-791395597
