### ISSUE TITLE
Is there any way to have scaling animation in the speeddial.

### ISSUE THREAD

**Issue by skylum1** [darioielardi/flutter_speed_dial#113]
The menu closes abruptly without any animation .
Basically I want this kind of behavior :-
https://pub.dev/packages/flutter_speed_dial_material_design

**Comment by prateekmedia** [comment]
> The menu closes abruptly without any animation .
> Basically I want this kind of behavior :-
> https://pub.dev/packages/flutter_speed_dial_material_design

I know I know, their's nothing I can currently do for it as I don't have sufficent knowledge on where the problem lies. Also are you using the latest version of the package from this git's repo?

**Comment by skylum1** [comment]
Yes , cloned this repo yesterday. Currently looking at the source code for animation controllers , will update if found any way to do this .

**Comment by Amir-P** [comment]
I made a small change in #130. Please check it out and leave a comment if there were any issues.
