### ISSUE TITLE
The speed dial flies to the center when fab is set to null

### ISSUE THREAD

**Issue by xcffl** [darioielardi/flutter_speed_dial#12]
When using the bottom navigation, it's possible to have a page without a fab (fab is set to null), as implemented in [the offical gallery demo app](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/tabs_fab_demo.dart ).

However, using flutter_speed_dial as the fab, when switch between pages with and without a fab, the fab flies to and from the center of the page, instead of falling down and flying back.

**Comment by tobilarscheid** [comment]
This is what the problem looks like:

![FloatingActionButtonBug](https://user-images.githubusercontent.com/5900890/78302123-7df54380-753a-11ea-922d-1080a79f278b.gif)

**Comment by prateekmedia** [comment]
Checkout V2 #90 it will be merged soon, it is based on #61, if it persists then reopen this issue

**Comment by andreystavitsky** [comment]
Same issue here with 
```
url: git://github.com/darioielardi/flutter_speed_dial.git   
ref: master
```

**Comment by andreystavitsky** [comment]
same issue on 2.3.5

**Comment by prateekmedia** [comment]
Checkout [new branch](https://github.com/darioielardi/flutter_speed_dial/tree/new), it has everything fixed.
