### ISSUE TITLE
Null safety support?

### ISSUE THREAD

**Issue by Arcturus5404** [darioielardi/flutter_speed_dial#123]
Is there any change this library getting null safety support?

**Comment by prateekmedia** [comment]
> Is there any change this library getting null safety support?

If you mean nullsafety support, then its already there in [nullsafety](https://github.com/darioielardi/flutter_speed_dial/tree/nullsafety) branch as also mentioned in the readme, pinned issue and pinned discussion.

**Comment by prateekmedia** [comment]
pub.dev will take time, so I can't say for that but nullsafety is now in master branch too.

**Comment by Arcturus5404** [comment]
Awesome! Thanks!
