### ISSUE TITLE
Custom Animated Icons

### ISSUE THREAD

**Issue by Designer007** [darioielardi/flutter_speed_dial#13]
Hi,

AnimatedIcons only provide a set of 14 icons to choose from. Is there a way to customize icons.

for instance, we have menu_close available.

But I want add_Close. Is it possible?

**Comment by Designer007** [comment]
Hi, thanks for the suggestion.

Would you possibly be able to help me with that, I'm fairly new to coding and Flutter. I am from a UX background.

**Comment by Designer007** [comment]
Thanks, will try it!

**Comment by marcjoha** [comment]
@darioielardi Any chance you can merge that branch into master? I need an "add to close" animation as well.

**Comment by KamilSvoboda** [comment]
You can easily implement custom animated icon with AnimatedSwitcher as a SpeedDial child.
```
Widget _speedDialIcon;
...
@override
initState() {
  _speedDialIcon = Icon(Icons.add);
  super.initState();
}
...
floatingActionButton: SpeedDial(
  child: AnimatedSwitcher(
	duration: const Duration(milliseconds: 100),
	transitionBuilder: (widget, animation) =>
		RotationTransition(
	  turns: animation,
	  child: widget,
	),
	child: _speedDialIcon,
  ),
  onOpen: () => setState(() {
	_speedDialIcon = Icon(
	  Icons.close,
	  key: UniqueKey(),
	);
  }),
  onClose: () => setState(() {
	_speedDialIcon = Icon(
	  Icons.add,
	  key: UniqueKey(),
	);
  }),
