### ISSUE TITLE
Publish to pub.dev

### ISSUE THREAD

**Issue by hoc081098** [darioielardi/flutter_speed_dial#132]
Please publish to pub.dev

**Comment by prateekmedia** [comment]
I know but here are @darioielardi words to me

>> Yes, I have the option to invite an “uploader” who would have admin rights on the package. Which is why I’d rather wait for a test period before doing that. I’m sure you can understand. I’d be glad to publish your work myself during that period.

> Dario Ielardi
on 31 Jan 2021, 7:23 pm
