### ISSUE TITLE
useRotationAnimation not working at all

### ISSUE THREAD

**Issue by Zeswen** [darioielardi/flutter_speed_dial#133]
It's not even being used in version `3.0.5`.

**Comment by prateekmedia** [comment]
> It's not even being used in version `3.0.5`.

Due to some changes it was removed, I think their are too many issues with bottomAppBar integration and Snackbar, looks like this needs a complete rewrite for the core functions, anyways thanks for the bug report.

**Comment by Zeswen** [comment]
No problem! I am making my own fork to avoid any problems with any issues not related with what I've commented.

**Comment by prateekmedia** [comment]
Checkout [new branch](https://github.com/darioielardi/flutter_speed_dial/tree/new), it has everything fixed.
