### ISSUE TITLE
MainAxisAlignment.end making children unaligned

### ISSUE THREAD

**Issue by Zeswen** [darioielardi/flutter_speed_dial#134]
For some reason there is a `MainAxisAlignment.end` at lines 436 and 455 of `speed_dial.dart`.
```dart
mainAxisAlignment: MainAxisAlignment.end,
crossAxisAlignment: CrossAxisAlignment.end,
```

This is causing the following behavior: 
![image](https://user-images.githubusercontent.com/37448151/111153298-10e38e00-8592-11eb-8fe7-449491e3fc77.png)

Make a property in the constructor or make it `MainAxisAlignment.center` by default.

**Comment by prateekmedia** [comment]
Checkout [new branch](https://github.com/darioielardi/flutter_speed_dial/tree/new), it has everything fixed.
