### ISSUE TITLE
Provide open argument to dialRoot

### ISSUE THREAD

**Issue by Zeswen** [darioielardi/flutter_speed_dial#135]
Instead of making the `dialRoot` property a `Widget`, use a `Widget Function(bool)` to provide the `open` argument to the function.

This would help a lot with custom buttons and avoid unnecessary memory allocation.

**Comment by prateekmedia** [comment]
Checkout [new branch](https://github.com/darioielardi/flutter_speed_dial/tree/new), it has everything fixed.

**Comment by prateekmedia** [comment]
As mentioned above new branch provide a full dialRoot experience.
