### ISSUE TITLE
PositionedDirectional has no way to change the end and bottom parameters

### ISSUE THREAD

**Issue by Zeswen** [darioielardi/flutter_speed_dial#136]
At lines 293 and 294 of `speed_dial.dart`, you cannot change the default `-16.0` end and bottom properties of it.

It's should be needed to fix unalignment problems on the dialRoot.

**Comment by prateekmedia** [comment]
Checkout [new branch](https://github.com/darioielardi/flutter_speed_dial/tree/new), it has everything fixed.

**Comment by prateekmedia** [comment]
I have completely eliminated the concept of margin Left and right and Now speed dial only depends on FloatingActingButtonLocation, so yeah this is fixed.
