### ISSUE TITLE
Hide on scroll animation goes to the left

### ISSUE THREAD

**Issue by TheMeanCanEHdian** [darioielardi/flutter_speed_dial#144]
I implemented the [example](https://github.com/darioielardi/flutter_speed_dial/blob/master/example/lib/main.dart) code for hiding the speed dial on a scroll but unlike the GIF in the read me it's animating off to the left.

Is there something I have missed here?

Flutter: v2.0.3
flutter_speed_dial: v3.0.5

https://user-images.githubusercontent.com/16025103/112739913-3f744800-8f46-11eb-9154-c2ce2f45b286.mp4

**Comment by prateekmedia** [comment]
> Flutter: v2.0.3
> flutter_speed_dial: v3.0.5

Can you try below code

```dart
SpeedDial(
    ...
    curve: Curves.bounceIn,
    ...
);

**Comment by TheMeanCanEHdian** [comment]
I get the same behavior when I manually set `curve: Curves.bounceIn`. I tried setting a few others at random, same behavior.

**Comment by TheMeanCanEHdian** [comment]
I put together a really basic app of just a list and the speed dial to confirm and showcase the issue.
https://github.com/TheMeanCanEHdian/Speed-Dial-Test

https://user-images.githubusercontent.com/16025103/112753626-4cc11f00-8fa6-11eb-8ecc-97c59927664d.mp4

**Comment by prateekmedia** [comment]
Ok let me investigate the issue then.

**Comment by prateekmedia** [comment]
Checkout [new branch](https://github.com/darioielardi/flutter_speed_dial/tree/new), it has everything fixed.

**Comment by prateekmedia** [comment]
It will go to the left if you will use latest dev version.
