### ISSUE TITLE
Make onTap etc work when label selected.

### ISSUE THREAD

**Issue by robertonic** [darioielardi/flutter_speed_dial#148]
Would it be possible to have the label behave the same way as the icon when it is selected. 

Users sometimes try to click the label rather than the icon and it is confusing if this does nothing.

**Comment by prateekmedia** [comment]
We already have it.

**Comment by prateekmedia** [comment]
in [`new`](https://github.com/darioielardi/flutter_speed_dial/tree/new) branch.

**Comment by robertonic** [comment]
That was quick. Thanks for the update.

**Comment by kapace** [comment]
It appears this is no longer working as of 
`  flutter_speed_dial: ^3.0.5`
Tapping on the SpeedDialChild label does not execute the onTap callback.

**Comment by prateekmedia** [comment]
Use the dev version from pub.dev
