### ISSUE TITLE
Use theme for default colors

### ISSUE THREAD

**Issue by shilangyu** [darioielardi/flutter_speed_dial#149]
https://github.com/darioielardi/flutter_speed_dial/blob/681b99f4d9d743835ed7e034860f6e87906da715/lib/src/speed_dial.dart#L391-L392

Why were such defaults chosen? It would seem to me that using colors from `Theme.of(context)` would be the sane defaults for widgets. Especially since `SpeedDial` often serves the purpose of a FAB, one would expect it to have the same colors as the material fab. If there is some reasoning behind it I would appreciate an explanation, thank you :)

Because of this I am forced to style the `SpeedDial` to look "defaulty" which seems backwards to me.

**Comment by prateekmedia** [comment]
@shilangyu Do you mean to keep the default fab color? or take it from theme context. Please elaborate more,

**Comment by shilangyu** [comment]
Additionally:

https://github.com/darioielardi/flutter_speed_dial/blob/681b99f4d9d743835ed7e034860f6e87906da715/lib/src/speed_dial.dart#L470

Why the system's brightness decides whether the speed dial should be in dark mode? Flutter apps allow to override it per app with `Theme.of(context).brightness`, so if my app uses light mode but the system is set to dark mode the `SpeedDial` looks out of place

**Comment by shilangyu** [comment]
> @shilangyu Do you mean to keep the default fab color? or take it from theme context. Please elaborate more,

Well, taking it from the theme context seems natural for me. This allows to customize it from the theme level. Of course `SpeedDial` has its own properties that cannot be taken from the theme context, then it makes sense to have arguments for it

**Comment by prateekmedia** [comment]
> https://github.com/darioielardi/flutter_speed_dial/blob/681b99f4d9d743835ed7e034860f6e87906da715/lib/src/speed_dial.dart#L470

This is Fixed in v4.

> Well, taking it from the theme context seems natural for me. This allows to customize it from the theme level. Of course SpeedDial has its own properties that cannot be taken from the theme context, then it makes sense to have arguments for it

This will be fixed in v4

Thanks for your contribution.
