### ISSUE TITLE
Set the FAB position on screen

### ISSUE THREAD

**Issue by shinayser** [darioielardi/flutter_speed_dial#15]
Hey man!
First of all, thank you so much for your awesome library!
I a using it in production in 2 apps but now I have to make some changes that currently it is impossible.

Right now is impossible to set the FAB position on screen, I can't set its margin (bottom and right margin). It has a fixed amount.

Is it too complicated for you provide us a way to set that margin as we desire? For example, set the right margin to 16 and bottom margin to 8.

Thank you so much and have a nice day!

**Comment by darioielardi** [comment]
Hey man, thank you so much for the appreciation!
I just implemented that feature in branch master, not published on pub yet, give it a try setting in your pubspec:
```
flutter_speed_dial:
    git: git://github.com/darioielardi/flutter_speed_dial.git
```
and then run `flutter packages get`
If the package updates correctly you should find two additional params, `marginRight` and `marginBottom`. Let me know if it works properly, in that case I'll publish it on pub.

**Comment by shinayser** [comment]
Hey man! I just tested and it works perfectly. Thankyou so much for your effort!
You my close this issue if you want :)

PS.: Just takign advantage of this issue, actually is it possible to set the FAB size?

**Comment by darioielardi** [comment]
Glad it works, I'm goin to publish the update asap.
Currently is not possible to set the fab size, I'll work on it sooner or later, obviously you can submit a PR if you need such a feature urgently.

**Comment by darioielardi** [comment]
Update just published.
Thank you!
