### ISSUE TITLE
Issues with child and activeChild (new branch)

### ISSUE THREAD

**Issue by Manuito83** [darioielardi/flutter_speed_dial#153]
Hello,

In older versions (e.g. 1.2.5) of the package, there was only one `child`. Now, the description of `activeChild` states "_This is the active child of the FAB, if specified it will animate b/w this and the child_". However, if there is no `activeChild`, the FAB appears blank.

```dart
SpeedDial(
    useRotationAnimation: false,
    overlayColor: Colors.grey,
    child: Container(
      width: 58,
      height: 58,
      decoration: BoxDecoration(
        border: Border.all(
          color: Colors.grey[800],
          width: 2,
        ),
        shape: BoxShape.circle,
        image: DecorationImage(
          fit: BoxFit.fill,
          image: AssetImage("images/icons/torn_t_logo.png"),
        ),
      ),
    ),
    visible: true,
    curve: Curves.bounceIn,
    children: [ ... ],
),
```
This is how it looks:

![image](https://user-images.githubusercontent.com/4816367/115689849-c4435d80-a35c-11eb-94a2-07a8be233f19.png)

But if there is no activeChild, when pressed, this is the result:

![image](https://user-images.githubusercontent.com/4816367/115689925-d7562d80-a35c-11eb-9474-095a09e8b65a.png)

In my opinion, if there is no `activeChild`, the same `child` should be used. It can be solved by duplicating the widget, but I don't think that makes much sense.

Independently of the `child` or àctiveChild`we use, when it's active, there is a border around the button:

![image](https://user-images.githubusercontent.com/4816367/115692114-fa81dc80-a35e-11eb-82da-417b364007ad.png)

This behaviour was correct in previous versions, such as 1.2.5 (sorry, last I tested).

**Comment by prateekmedia** [comment]
Thanks for the bug report, It should be fixed now.
