### ISSUE TITLE
Adding Key to speed_dial

### ISSUE THREAD

**Issue by brownAddict** [darioielardi/flutter_speed_dial#154]
Sorry, this is my first time.

If I add a key to my speed_dial, it throws this error message 

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:[39;49m
Multiple widgets used the same GlobalKey.

The key [GlobalKey#486a1] was used by multiple widgets. The parents of those widgets were:
- Listener(listeners: [down], behavior: deferToChild, renderObject: RenderPointerListener#cb8a1 relayoutBoundary=up11)
- AnimatedBuilder(animation: AnimationController#cc2c5(⏮ 0.000; paused), state: _AnimatedState#5d0a3)

A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack
GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>.<anonymous closure>
_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)[39;49m
GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>[39;49m
_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)[39;49m
GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure>[39;49m
═══════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Multiple widgets used the same GlobalKey.
══════════════════════════════════════════════════════════════════

Below is my speeddialcode

```
final GlobalKey<ScaffoldState> _speedDialKey = GlobalKey<ScaffoldState>();

Widget build(BuildContext context) {
...
  SpeedDial(
    key: _speedDialKey,
    animatedIcon: AnimatedIcons.menu_close,
    visible: true,
    curve: Curves.bounceIn,
    children: [
      SpeedDialChild(
        child: Icon(Icons.category_outlined),
        onTap: () => Navigator.pushNamed(context, '/add-category'),
        label: 'Add Inventory Category',
      ),
    ],
  );
...
```

Putting that key works as it should but it throws that error. If i put that key in speedDialChild, it works without any error.

flutter_speed_dial: ^3.0.5

**Comment by brownAddict** [comment]
I just used the latest (unreleased version - see below) and the key worked fine without any error. So, I will close this.

flutter_speed_dial: 
    git:
      url: git://github.com/darioielardi/flutter_speed_dial.git
      ref: new

**Comment by kevin4dhd** [comment]
same error

**Comment by prateekmedia** [comment]
@kevin4dhd Can you post the full error with a minimal reproducing example, I am not facing the same error in the latest version:
<details>
<summary>My Code</summary>

```dart
SpeedDial(
          key: GlobalKey(),
          ...
)
```
</details>
