### ISSUE TITLE
Implement visibility also for SpeedDialChild

### ISSUE THREAD

**Issue by enricobenedos** [darioielardi/flutter_speed_dial#158]
Good morning,

sometimes I need to show only some children when using `SpeedDial` FAB. At the moment I need every time to write a lot of boilerplate in order to achieve that.

Is it possible to implement a `visible` boolean property (or function) in order to hide specific children on certain conditions? Normally with standard widgets it is possible to use `Visibility` widget but in this case `SpeedDial` children are of type `SpeedDialChild` and it is not possible to do that.

Thank you

**Comment by prateekmedia** [comment]
Yes it is possible, will implement it when I am free.

**Comment by prateekmedia** [comment]
Should be fixed in latest SpeedDial v 4.0.0-dev.1
