### ISSUE TITLE
Extremely slow animation

### ISSUE THREAD

**Issue by ozzy1873** [darioielardi/flutter_speed_dial#16]
My app has a ListView and fab. I replaced the fab with the speed dial plugin. I copy and pasted the _renderSpeedDial() method from the example and tweaked it just enough to get it to compile. Initially, performance is great. However, I noticed that the fab response time gets slower and slower. Within a short time, it can take 30+ seconds for the fab to respond. Steps to reproduce:

1) Force close the app and re-open it.
2) Note that the fab response is very fast.
3) Do not interact with the app for a few minutes.
4) Note that the fab response is noticeably slower.

Performing steps 3-4 several times will lead to a response time of 10's of seconds. The performance of the rest of the app is unaffected; ListView scrolling performance does not slow down. Do you have any idea what might be happening?

**Comment by darioielardi** [comment]
That looks weird.
Would you provide a repo to reproduce your case? I can't really imagine what might be happening.

**Comment by ozzy1873** [comment]
I found the problem: calling _renderSpeedDial in the build method, which gets called often. If I call _renderSpeedDial just once in initState and pass the result to floatingActionButton in build, then I do not experience this performance degradation.

**Comment by darioielardi** [comment]
Glad you solved! Closing.
