### ISSUE TITLE
Snackbar doesnt show if have SnackbarBehaviour.floating along with Flutter SpeedDial

### ISSUE THREAD

**Issue by sgshivamgarg8** [darioielardi/flutter_speed_dial#164]
Snackbar doesnt show if we have Flutter SpeedDial in the screen and Snackbar has property of floating instead of fixed.
No errors in console.
Snackbar shows if Behaviour is set to fixed (causes FAB to go up)
Also works if Flutter's default FAB is used.

**Comment by prateekmedia** [comment]
Ok lemme see then, it should work if it works for normal fab.

**Comment by sgshivamgarg8** [comment]
Thanks

**Comment by prateekmedia** [comment]
Sorry I cannot reproduce the same error, it works for me under linux with behaviour set to floating.

Make sure you are using latest dev version of speeddial 4.0.0-dev.1

![Screenshot_20210529_235042](https://user-images.githubusercontent.com/41370460/120081050-1eaca800-c0d9-11eb-9ad4-3704968d4757.png)

<details>
<summary>
Code I used
</summary>

```dart
SpeedDialChild(
              ...
              onTap: () => ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                content: Text(("Third Child Pressed")),
                behavior: SnackBarBehavior.floating,
              )),
              ...
)
```

</details>

**Comment by sgshivamgarg8** [comment]
I was using v3.0.5 as only it was available as stable (default version).
It might work on 4.0.0-dev version.
I will try tomorrow and let you know.

**Comment by prateekmedia** [comment]
> I was using v3.0.5 as only it was available as stable (default version).
> It might work on 4.0.0-dev version.
> I will try tomorrow and let you know.

The dev version is the future so you should try it and report bugs if any.

**Comment by sgshivamgarg8** [comment]
Yes its working in v4
