### ISSUE TITLE
Add two speed dials on a single page.

### ISSUE THREAD

**Issue by agzy** [darioielardi/flutter_speed_dial#167]
I am having 10-12 speed dial children. On smaller screens some speed dial children are not visible. Is there any way to change the column for speed dial children after a fixed number?

**Comment by agzy** [comment]
If it's not possible, is there any way to have two speed dials on a  single page?

**Comment by prateekmedia** [comment]
> I am having 10-12 speed dial children. On smaller screens some speed dial children are not visible. Is there any way to change the column for speed dial children after a fixed number?

If you follow Material design guidelines then you will know that max number of items in one speeddial is 6 and 12 items are not recommended as it will confuse the users.

![Screenshot_20210606-071707_Firefox Beta](https://user-images.githubusercontent.com/41370460/120909865-4d0d2300-c697-11eb-9bb7-2ab961ff2abc.jpg)

**Comment by agzy** [comment]
> If it's not possible, is there any way to have two speed dials on a single page?

Can it be done?

**Comment by prateekmedia** [comment]
> > If it's not possible, is there any way to have two speed dials on a single page?
> 
> Can it be done?

Let's see then, I don't have time for it currently, Any pull request or suggestion on how to do it is welcome. 

I am thinking of using `Wrap` to implement it but I don't have other clues for it

**Comment by luca-colazzo** [comment]
Speed dial is designed as a FAB, so it's designed to be only one, following material design.
So, this won't be implemented. You are always free to do that and open a PR
