### ISSUE TITLE
Disable entering/exit animation

### ISSUE THREAD

**Issue by mucyomiller** [darioielardi/flutter_speed_dial#17]
![issue_extra_small](https://user-images.githubusercontent.com/11447549/53884451-44df5c80-4024-11e9-8735-3ebf8bdc0781.gif)

How can I remove that entering and exit animation? just show fab without animating it thanks.

**Comment by mucyomiller** [comment]
nevermind I removed from floatingActionButton of Scaffold and placed at the end of Stack on Home route only and solved my issue thanks!

**Comment by OliverKong** [comment]
Hi,Now I also had this problem now, can U show me the detailed method for resolving the issue,Thank U and best wishes for U.
