### ISSUE TITLE
Setting Initial state open

### ISSUE THREAD

**Issue by henry8th** [darioielardi/flutter_speed_dial#170]
Hello 👋🏽,

Thanks for the great lib.
Was wondering if you can set the initial state to open?

**Comment by prateekmedia** [comment]
Yes, use isOpenOnStart or something like that property to open by default. If you have any issue then ask me to reopen this.

**Comment by henry8th** [comment]
Hi apologies I'm unable  to find the property on the speeddial widget, iv
looked through it several times but must be missing it

**Comment by prateekmedia** [comment]
I think you are not in the dev branch, are you?

Dev branch has that + many many features.

**Comment by henry8th** [comment]
That would be it.. thank you :)
