### ISSUE TITLE
Animation issue when changing routes

### ISSUE THREAD

**Issue by hnrq** [darioielardi/flutter_speed_dial#171]
I'm using SpeedDial in a project where the Floating action button should appear in only one screen. When using a regular FAB, the button disappears with a shrinking animation by default. However, when I replace FloatingActionButton by SpeedDial, the animation breaks, and the button goes up and shrinks before disappearing. Does anybody know a workaround for that?

**Comment by prateekmedia** [comment]
Use flutter speed dial dev version.

**Comment by hnrq** [comment]
Thanks!
