### ISSUE TITLE
Is there any way to switch position of child and labelWidget in SpeedDialChild?

### ISSUE THREAD

**Issue by Kotaro666-dev** [darioielardi/flutter_speed_dial#172]
Hi there.

I am implementing 3 SpeedDialChild widgets in SpeedDial children.

By default, SpeedDialChild displays child on the right side and labelWidget on the left side.
I use the child widget as rounded Icon and the labelWidget as text.

Instead of this default, I want to implement only one of 3 SpeedDialChild widgets like this;  child on the left side and labelWidget on the right side.

Is there any way to switch position of child and labelWidget in SpeedDialChild?

**Comment by prateekmedia** [comment]
Yes there is a way in speed dial dev version by using switchLabelPosition property.


If you don't want to use that then you can just remove icon and specify your custom labelWidget for SpeedDialChild

**Comment by Kotaro666-dev** [comment]
@prateekmedia 

Thank you for your response.

> Yes there is a way in speed dial dev version by using switchLabelPosition property.

I checked and read the source code. However, I am assume this switchLabelPosition parameter affects all of SpeedDialChild widgets. My goal is to make this change to one of three SpeedDialChild widgets. I am afraid this cannot help me.

> If you don't want to use that then you can just remove icon and specify your custom labelWidget for SpeedDialChild

I thought about it and tried to remove icon, which is child parameter by assigning null. 

```
SpeedDialChild(
          child: null,
          backgroundColor: Colors.black.withOpacity(0.01),
          elevation: 0,
          labelWidget: Text(
            'Help',
            style: const TextStyle(
              color: Colors.white,
              fontWeight: FontWeight.bold,
              fontSize: 20,
            ),
          ),
          onTap: () {},
        ),
```

However, the space of child still exists in SpeedDialChild widget and cannot be removed entirely. This happens because SpeedDialChild's child has buttonSize field, which is assigned from parental widget SpeedDial.

```
List<Widget> _getChildrenList() {
    final singleChildrenTween = 1.0 / widget.children.length;

    return widget.children
        .map((SpeedDialChild child) {
          int index = widget.children.indexOf(child);

          var childAnimation = Tween(begin: 0.0, end: widget.buttonSize).animate(
            CurvedAnimation(
              parent: this._controller,
              curve: Interval(0, singleChildrenTween * (index + 1)),
            ),
          );

          return AnimatedChild(
            animation: childAnimation,
            index: index,
            key: child.key,
            visible: _open,
            dark: widget._dark,
            backgroundColor: child.backgroundColor,
            foregroundColor: child.foregroundColor,
            elevation: child.elevation,
            buttonSize: widget.buttonSize, <------------------------------------ HERE
            child: child.child,
            label: child.label,
            labelStyle: child.labelStyle,
            labelBackgroundColor: child.labelBackgroundColor,
            labelWidget: child.labelWidget,
            onTap: child.onTap,
            onLongPress: child.onLongPress,
            toggleChildren: () {
              if (!widget.closeManually) _toggleChildren();
            },
            shape: child.shape,
            heroTag: widget.heroTag != null ? '${widget.heroTag}-child-$index' : null,
            childMarginBottom: widget.childMarginBottom,
            childMarginTop: widget.childMarginTop,
          );
        })
        .toList()
        .reversed
        .toList();
  }
```

I really appreciate to you if you could help me solving problem.

**Comment by prateekmedia** [comment]
I am again asking you, are you on dev version of this package? If not update your package to latest dev version from pub.dev

And if you are already on dev version then you can easily remove child parameter from SpeedDialChild, and there will be no space left.
https://github.com/darioielardi/flutter_speed_dial/blob/acd680e3cdc901e22057763888bd0b8eb46e1fa5/lib/src/animated_child.dart#L117-L136

You can clearly see on line no. 126 if child is null, its container  would not be rendered.

**Comment by Kotaro666-dev** [comment]
No I am not on dev version of this package since my project is not ready to Null Safety version at all.

I believe I can accomplish my goal by updating to dev version. 

I will close this issue by myself. Thank you very much for your advice!

**Comment by prateekmedia** [comment]
> No I am not on dev version of this package since my project is not ready to Null Safety version at all.
> 
> I believe I can accomplish my goal by updating to dev version.
> 
> I will close this issue by myself. Thank you very much for your advice!

Null safety is backward compatible, you can use it in non null safe code too.
