### ISSUE TITLE
Any way to toggle visibility of children?

### ISSUE THREAD

**Issue by meghead** [darioielardi/flutter_speed_dial#173]
I tried wrapping Flutter's Visibility widget on the icon but then I get a blank white icon where there should be an empty space.

The SpeedDialChild itself can't be wrapped with the Visibility Widget. So I need another option.

I'd like to be able to do;

if (thisid == thatid){  
SpeedDialChild;
} else { 
empty space;
 }

Is there a way to do this?

**Comment by prateekmedia** [comment]
Hay @meghead,

Why du you want else part, jast use 
```
if (thisid==thatid) SpeedDialChild(
...
) 
```
and thats it, Okey?

Sorry far my badass inglish, I'm still learning and using autocorect.
