### ISSUE TITLE
How to Programmatically Open the Dial

### ISSUE THREAD

**Issue by fernan542** [darioielardi/flutter_speed_dial#175]
Hello, my set-up is modularized. The button is inside a separated Stateless widget and I want to open the dial when it was clicked. I can't find any keys to access the speed-dial widget so I'm not able to do it. Any suggestion? Thanks.

**Comment by prateekmedia** [comment]
> Hello, my set-up is modularized. The button is inside a separated Stateless widget and I want to open the dial when it was clicked. I can't find any keys to access the speed-dial widget so I'm not able to do it. Any suggestion? Thanks.

Firstly use the dev version of this package from pub.dev, after that you can follow `openCloseDial` property or can follow the tutorial for how to use it here https://github.com/darioielardi/flutter_speed_dial#close-on-willpop.

**Comment by fernan542** [comment]
Oh, didn't see that sorry. Thanks for this package. :)
