### ISSUE TITLE
Tooltip prevents longpress opening

### ISSUE THREAD

**Issue by yan-064** [darioielardi/flutter_speed_dial#176]
Hi,

When the tooltip property is set, it prevents the opening with the longpressevent.

**Comment by prateekmedia** [comment]
> prevents

Just remove the tooltip then?

**Comment by yan-064** [comment]
Sure I did. I just wanted to focused on this potential bug.


Le mer. 7 juil. 2021 à 16:32, Prateek SU ***@***.***> a
écrit :
