### ISSUE TITLE
Feature request: Only open on long press

### ISSUE THREAD

**Issue by ehhc** [darioielardi/flutter_speed_dial#18]
I wish it would be possible to to a normal action on press and only open the child buttons on long press. Do you see any options how this could be done? 

Thanks in advance

**Comment by darioielardi** [comment]
I think that's totally possible, but the default behavior should be the current one. I could work on the implementation next week, but PRs are always welcome!

**Comment by ehhc** [comment]
i fear since you updated your code, it's not as easy possible as before.. the reason is that you're using a AnimatedFloatingButton which cannot have a long-press-handler (because the long press triggers the label..)...
Previously it was possible.. see my commit (i know, it's not a PR, but i was unsure about it at that time..)

Anyway: should i close the issue since its now complicated to implement it? (and it seems, nobody but me wants it anyway :D )?

**Comment by darioielardi** [comment]
The `AnimatedFloatingButton` is actually a custom widget provided by the library itself. It would be totally possible to implement the behavior you need, just add a function parameter to override the press callback and a boolean parameter to toggle the dial on long press.
Let me know if you need help with the implementation, even if you're not sure I can review it and eventually fix it.

**Comment by ehhc** [comment]
@darioielardi thanks for the encouraging reply. I mentioned the wrong class.. i meant `FloatingActionButton` instead of `AnimatedFloatingButton`. In that class, no longPress is intended. Anyway: i noticed, that i can combine it with a gestureListener (even if not intended) to work around that.. You would have a look at my solution? In that case, i'll open an PR :)

Thanks again :)

**Comment by darioielardi** [comment]
The `GestureDetector` looks a pretty valid solution, but I noticed you've also modified the behavior of the `BackgroundOverlay`, I'm not sure it should act as the main button does when the `onPress` parameter is defined, it should probably keep the old behavior, long press on the background overlay does not really make sense. Apart from that your implementation is fine, if you fix the overlay behavior ( and please format your code with the dart formatter ) I'd be happy to merge the PR :)

**Comment by ehhc** [comment]
hi @darioielardi  i removed the longPress-stuff in the overlay... it was a leftover from my first try and i forgot to delete it.. furthermore, i formated it with `flutter format .`

**Comment by darioielardi** [comment]
Merged, thank you for the contribution, nice work :)

**Comment by ehhc** [comment]
Thanks :)
