### ISSUE TITLE
Push fab above after generating a snackbar

### ISSUE THREAD

**Issue by christianfl** [darioielardi/flutter_speed_dial#185]
Hey, thanks for this beautiful plugin!

When using the official fab and generating a snackbar, the snackbar pushes the fab above so that both of them are still visible. The fab with this plugin stays in the same place. Is it possible to get the same behaviour as the original fab somehow?

Tried with v4.1.0

**Comment by prateekmedia** [comment]
I don't think so, This plugin uses original fbn so it will have the same behaviour.

**Comment by christianfl** [comment]
@prateekmedia I'm not quite sure I understood your answer correctly. So you think it is not possible?

**Comment by prateekmedia** [comment]
Can you try running the example app and see if it's working or not maybe
its related to your code


In example app open speed and tap top speed child child then you will see a
snack bar which is raising the speed dial too.

So it's possible.

**Comment by christianfl** [comment]
Thanks for hinting me to that @prateekmedia 

It works there, very strange. Couldn't figure out why this is happening even after looking into the example source code. I will further look into that and otherwise close this issue.
