### ISSUE TITLE
SpeedDialChild icon color is faded when using an svg image

### ISSUE THREAD

**Issue by nickwri** [darioielardi/flutter_speed_dial#186]
I'm using a speeddialchild as follows:

        SpeedDialChild(
          child: SvgPicture.asset(
              MyImages.sampleSmall,
              color: Colors.white
          ),
          backgroundColor: Colors.blue,
          foregroundColor: Colors.white,
          label: 'Record Sample',
          labelStyle: TextStyle(fontSize: 12.0),
          onTap: controller.onTapRecordSample,
        ),

The Record Sample child button icon is not white, its more of a washed out grey:

![image](https://user-images.githubusercontent.com/16494391/127307739-605230ea-5fd8-43e6-853d-3672caf8cd53.png)

When using an icon, it shows as pure white:

![image](https://user-images.githubusercontent.com/16494391/127308061-138f8d2b-2487-41a7-b792-11f1c6bff42e.png)

**Comment by prateekmedia** [comment]
This is not related to speed dial, can you check your svg for it.

**Comment by nickwri** [comment]
You're right - svg has an opacity value, which I've changed to 1.0. Thanks for quick response
