### ISSUE TITLE
Axis overlay on long press in Apps and on hover in Web

### ISSUE THREAD

**Issue by BenPoell** [darioielardi/flutter_speed_dial#189]
I faced some weird thick axis lately from the main button to the children:

App (long press press main button):
![image](https://user-images.githubusercontent.com/24900930/128813218-76e84248-c6b9-4abe-962a-4d9d1fe49fd2.png)

Web (hover main button):
![image](https://user-images.githubusercontent.com/24900930/128813194-9c635ffc-2fa0-4870-9fb5-556bcf90a3d6.png)

Can I somehow influence that?

**Comment by prateekmedia** [comment]
That's the tooltip, set it using the top tip property.

**Comment by BenPoell** [comment]
I see, would it make sense to remove it, when it's empty? I couldn't find a way to influence that tbh and it confuses the users (especially on hover in Web).

Or would a different position make sense?

**Comment by prateekmedia** [comment]
Can you try the same on web by using FloatingActionButton instead of SpeedDial, I think this might be an issue with it and the web platform.

**Comment by BenPoell** [comment]
Alright, what I found out is following for floatingActionButton:

- when `tooltip == null` it works fine, no tooltip is shown
- when `tooltip == ""` the tooltip is shown empty (as in the screenshot above)

```
floatingActionButton: FloatingActionButton(
  child: Icon(
    Icons.add,
  ),
  tooltip: "",
  onPressed: () {},
),
```
![image](https://user-images.githubusercontent.com/24900930/129260922-64025da7-b572-4fdf-bf19-17f41f45ca03.png)

here in `BackgroundOverlay` is a null check and I guess this is triggering that behaviour:
![image](https://user-images.githubusercontent.com/24900930/129260570-2507fd89-cac3-4e3f-97bd-d3475512aa88.png)

**Comment by prateekmedia** [comment]
Fixed in latest version.
