### ISSUE TITLE
Maintainer Wanted

### ISSUE THREAD

**Issue by prateekmedia** [darioielardi/flutter_speed_dial#190]
If you are interested in maintaining this repository then you can
- Reply to this issue regarding how can you help maintain this repository
- Contact @darioielardi on telegram or email
- You can respond to this [issue](https://github.com/fluttercommunity/community/issues/75) on `fluttercommunity`.

**Comment by p0wl90** [comment]
Maybe this is of interest for you? 

https://github.com/fluttercommunity/transfer-guide

**Comment by prateekmedia** [comment]
@p0wl90 I know, but they are not approving the issue as mentioned in my post too.

**Comment by p0wl90** [comment]
Ah, I'm very sorry that I overlooked that you already requested that!

**Comment by luca-colazzo** [comment]
I can help you mantaining the repo if you want

**Comment by prateekmedia** [comment]
@luca-colazzo Okay, I will contact dario regarding it on Telegram.

**Comment by prateekmedia** [comment]
@luca-colazzo As said before, Dario has invited you to join the repo, hope you will solve issues and help maintain the repo.

I will be here if you need some help regarding the code.

**Comment by prateekmedia** [comment]
@luca-colazzo Please tell me your pub.dev email so that I can add you as a maintainer over there.

**Comment by luca-colazzo** [comment]
lucac99l4@gmail.com

**Comment by prateekmedia** [comment]
Maintainer is still wanted.
