### ISSUE TITLE
Discrepancy in documentation guidelines

### ISSUE THREAD

**Issue by KartikShrivastava** [darioielardi/flutter_speed_dial#197]
Hi,

If I'm understanding it correctly then.
Documentation in [line 80](https://github.com/darioielardi/flutter_speed_dial/blob/8f867c045d8d13953f2edd27250ef1b11d4075eb/lib/src/speed_dial.dart#L80) (as of this writing) of ```speed_dial.dart``` states a warning that if ```closeManually``` is true then overlay won't be rendered, but actually it does draws the overlay. Only after explicitly setting ```renderOverlay``` to false it doesn't draws overlay.

Is that okay or something is wrong?

**Comment by prateekmedia** [comment]
Ah yes that info is old, currently this repository has no maintainer that's why there are some loose ends, will fix it sometime.

**Comment by KartikShrivastava** [comment]
No problem, I can fix it if contributions are welcomed.

Also there are few crashes happening on hot reload(related to overlay flag) will try to write out instructions to reproduce it if time permits.

**Comment by luca-colazzo** [comment]
Any news on the steps to reproduce?

**Comment by prateekmedia** [comment]
I have fixed the documentation of closeManually and renderOverlay.
