### ISSUE TITLE
Dart SDK version issue

### ISSUE THREAD

**Issue by jjzoob** [darioielardi/flutter_speed_dial#2]
/Users/JerryChen/flutterDev/flutter/bin/flutter --no-color packages get
Running "flutter packages get" in example...
The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.

Because flutter_speed_dial_example depends on flutter_speed_dial from path which requires SDK version >=1.19.0 <2.0.0, version solving failed.
pub get failed (1)
Process finished with exit code 1

**Comment by darioielardi** [comment]
I'm sorry for the inconvenient, just fixed, now should work.
Let me know if I can close.
