### ISSUE TITLE
SpeedDial gone when spam notifier 

### ISSUE THREAD

**Issue by callmejm** [darioielardi/flutter_speed_dial#200]
When keep spamming the notifier , SpeedDial will gone forever

**BottomNavigationBar**

      onTap: (index){
        if(index == 4){
          _openFabMenu.value = true;
        }
        if(index != 4){
          controller.jumpToPage(index);
          currentIndex.value = index;
        }
      },

**Scaffold**

    floatingActionButton: SpeedDial(
        backgroundColor: Colors.transparent,
        overlayColor: Colors.white,
        overlayOpacity: 0,
        buttonSize: 0,
        openCloseDial: _openFabMenu,
        childrenButtonSize: 55,
        children: [
          SpeedDialChild(),
          SpeedDialChild(),
        ]
      ),

**Video**

https://user-images.githubusercontent.com/6957533/134141893-94fe156f-d6f0-4cc6-a111-4103d3bc8e7a.mp4

**Comment by prateekmedia** [comment]
Any errors or logs?

**Comment by callmejm** [comment]
no error

**Comment by prateekmedia** [comment]
Did the same, works fine even after spamming multiple times.

Can you check if this works on the official example project [here](https://github.com/darioielardi/flutter_speed_dial/tree/master/example).

**Comment by callmejm** [comment]
@prateekmedia example is 4.4.0, when I try 4.4.0, getting error
![image](https://user-images.githubusercontent.com/6957533/134454310-0766333d-169f-47fd-80aa-d594ba340c46.png)

**Comment by callmejm** [comment]
@prateekmedia I using `onOpen` and `onClose` for log spamming, when it gone, it stop at `onOpen` , and then whatever I spam `onOpen` and `onClose` not trigger anymore

**Comment by prateekmedia** [comment]
@callmejm update your flutter to v2.5.0
