### ISSUE TITLE
Possible regression in 4.4.0; Required named parameter 'vsync' must be provided

### ISSUE THREAD

**Issue by Tobiaswk** [darioielardi/flutter_speed_dial#203]
After upgrading to 4.4.0 we've run into this regression;
`flutter_speed_dial-4.4.0/lib/src/animated_floating_button.dart:86:23: Error: Required named parameter 'vsync' must be provided.`

Flutter --version;
```
Flutter 2.2.3 • channel unknown • unknown source
Framework • revision f4abaa0735 (3 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

We're using the 2.2.3 tag.

**Comment by prateekmedia** [comment]
Update your flutter to flutter 2.5 using `flutter upgrade` command

**Comment by prateekmedia** [comment]
Upgrade to package v 4.4.0+1

**Comment by smolugu** [comment]
any other way to fix this problem? I can't upgrade to flutter 2.5 because of dependencies

**Comment by prateekmedia** [comment]
@smolugu you can fork this, add vsync and use git url as a source instead of pub.dev in pubspec.yaml

**Comment by smolugu** [comment]
ok great! Thank you!!
