### ISSUE TITLE
Has this issue been resolved?

### ISSUE THREAD

**Issue by Gustavo-alves-fernandes** [darioielardi/flutter_speed_dial#204]
Has this issue been resolved?

**Comment by prateekmedia** [comment]
What issue?

**Comment by Gustavo-alves-fernandes** [comment]
Null check operator used on a null value - on toggleOverlay's dialkey
globalPaintBounds

Em dom, 26 de set de 2021 11:22, Prateek SU ***@***.***>
escreveu:

**Comment by prateekmedia** [comment]
Not resolved, https://github.com/darioielardi/flutter_speed_dial/issues/198

**Comment by Garrison88** [comment]
Any update on this issue? @prateekmedia
