### ISSUE TITLE
Change "childrenButtonSize" from double to Size

### ISSUE THREAD

**Issue by TolgaYld** [darioielardi/flutter_speed_dial#210]
Hi,
can you change the property of "childrenButtonSize" from "double" to "Size"? So you could use other shapes besides circles (e.g. rectangles).

thx in advance. :)

**Comment by CostierLucas** [comment]
Yes I agree ! :)

**Comment by luca-colazzo** [comment]
#221

**Comment by prateekmedia** [comment]
Will close this when new version is published, with updated CHANGELOG.

**Comment by luca-colazzo** [comment]
> Will close this when new version is published, with updated CHANGELOG.

Yeah, that's a breaking change

**Comment by prateekmedia** [comment]
I have updated the version number to 5.0.0, To use that be sure to use latest flutter and dart version.
