### ISSUE TITLE
Button not centered aligned if children's button size is too big

### ISSUE THREAD

**Issue by Silfalion** [darioielardi/flutter_speed_dial#213]
As mentioned the buttons look to be aligned left if they get over 60, is there a fix for it pls?

**Comment by Silfalion** [comment]
same issue still occurs. Tried to fiddle around with the library and the alignment can be adjusted almost precisely by changing the offset, but I'm not familiar enough with the code to center right above the dial. Any ideas?

**Comment by prateekmedia** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/41370460/139527753-0956f599-b229-49ca-ab20-987c648d5726.png)
How much centering do you want.

**Comment by Silfalion** [comment]
Haha I did think that I didn't express myself right. The alignement is for the children regarding the dial not the other way around. Will show an example.

**Comment by Silfalion** [comment]
![image](https://user-images.githubusercontent.com/23188369/139527846-656d4d28-c254-4d07-9f71-0a7372987692.png)

**Comment by prateekmedia** [comment]
@Silfalion Yes that's a bug which I don't know how to fix, but will try to fix.

**Comment by Silfalion** [comment]
Thank you so much! Though if you decide you don't to spend time with it and get an idea midway I'd be happy to fix it. 

A very crude way of fixing it would be to add an Offset argument to speedial I think, not very elegant but does the job. If you think that it has some potential I can give it a try.

**Comment by prateekmedia** [comment]
@Silfalion I have fixed it in v 4.6.6 the same way, I will push it in few minutes.

**Comment by Silfalion** [comment]
@prateekmedia dang you're Git Flash. Really really appreciate it, thanks man.

**Comment by prateekmedia** [comment]
Done.
