### ISSUE TITLE
SpeedDial prevents swiping gesture to return to previous page

### ISSUE THREAD

**Issue by jonmountjoy** [darioielardi/flutter_speed_dial#216]
If SpeedDial is on a Scaffold, on a page that you navigate to, you will no longer be able to swipe back.  

SpeedDial appears to prevent all back navigation, at least on iOS.  

The demo app https://github.com/jonmountjoy/speeddialbug shows a home page and 3 buttons to navigate to 3 pages using a standard `Navigator.of(context).push(...)`.

1. The first page has a standard scaffold. You will be able to swipe back.
2. The second page has a SpeedDial.  Swiping no longer works.
3. The third page has a standard FloatingActionButton.  You will be able to swipe back.

Is this a bug? I can't seem to find it in the documentation, nor a way to disable the disabling.

**Comment by jonmountjoy** [comment]
Thank you @prateekmedia - I appreciate that change!

PS. I wonder if you need another edge case for `kIsWeb`.  My instinct is that the default UI for web, when someone hits back, is not to close the menu, but to actually go back.

**Comment by paulosousadias** [comment]
It still got an issue with this.
I'm using the CupertinoPageTransitionsBuilder even on Android. (I know this is a WillPopScope issue: https://github.com/flutter/flutter/issues/14203.)

Just to place here a workaround that worked for me and might be helpful to others.
The workaround is to make use of the already provided ```{ValueNotifier<bool>? openCloseDial}``` on a builder:

``` dart
...
ValueNotifier<bool> isDialOpen = ValueNotifier(false);
...

openCloseDial != null
      ? ValueListenableBuilder(
          valueListenable: openCloseDial,
          builder: (context, _, __) => SpeedDial(
            closeDialOnPop: openCloseDial!.value,
            openCloseDial: openCloseDial,
            animatedIcon: animatedIcon,
            visible: visible,
            children: children,
          ),
        )
      : SpeedDial(
          animatedIcon: animatedIcon,
          visible: visible,
          children: children,
        );
...
```
