### ISSUE TITLE
Speed dial freezes the UI when closed

### ISSUE THREAD

**Issue by alod2019** [darioielardi/flutter_speed_dial#217]
Speed dial freezes the UI when closed if Scaffold is relocated when the widget tree rebuilds, see the video.
This is the code to reproduce the issue.
```
import 'package:flutter/material.dart';
import 'package:flutter_speed_dial/flutter_speed_dial.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _showSpeedDual = false;

  @override
  Widget build(BuildContext context) {
    final scaffold = Scaffold(
      appBar: AppBar(
        title: Text(_showSpeedDual ? 'Speed Dial View' : 'Home View'),
      ),
      body: _showSpeedDual
          ? const SizedBox.expand()
          : Center(
              child: ElevatedButton(
                onPressed: () => setState(() => _showSpeedDual = true),
                child: const Text('Show Speed Dial'),
              ),
            ),
      floatingActionButton: _showSpeedDual
          ? SpeedDial(
              icon: Icons.menu,
              activeIcon: Icons.close,
              children: [
                SpeedDialChild(
                  child: const Icon(Icons.message),
                  label: 'Dummy item',
                  onTap: () {},
                ),
                SpeedDialChild(
                  child: const Icon(Icons.home),
                  label: 'Back to Home View',
                  onTap: () => setState(() => _showSpeedDual = false),
                ),
              ],
            )
          : null,
    );
    return _showSpeedDual ? SizedBox.expand(child: scaffold) : scaffold;
  }
}

```

https://user-images.githubusercontent.com/52775233/140291710-0d62e8cd-68b2-451b-942c-7928ab0fd834.mp4

**Comment by alod2019** [comment]
And that's how the widget tree looks after rebuild
![speed_dial_freeze_widget_tree](https://user-images.githubusercontent.com/52775233/140292281-7dc594a0-238d-4354-a1e8-f68f452aad22.png)

**Comment by prateekmedia** [comment]
That would happen, cause your speeddial's overlayentry is not disposed, Also your speed dial childrens are floating cause the parent dial is removed without closing the dial first.

**Comment by alod2019** [comment]
> That would happen, cause your speeddial's overlayentry is not disposed, Also your speed dial childrens are floating cause the parent dial is removed without closing the dial first.

But closeManually flag is set to false by default  and _SpeedDialState.dispose() is called.  What else need be done ?

 Everything works fine if replace 
 ```
 return _showSpeedDual ? SizedBox.expand(child: scaffold) : scaffold;
 ```
 with just 
 ```
 return scaffold;
```
but it's not always possible to keep Scaffold without wrapping it by other widgets .
In my case that it need to be conditionally wrapped by BlocProvider and BlocBuilder and that messes Speed Dial behavior as described.

**Comment by luca-colazzo** [comment]
The SpeedDial is meant to work as a FAB into the Scaffold. If you wrap the scaffold into other widgets that will be replaced, be sure to override the dispose method and do that correctly, this can't be done in the dispose method of SpeedDial.
Also onTap has to be triggered when the button is tapped, otherwise it was: onTapAfterClose. If the SpeedDial is closed, due to its State, onTap can't be called, you just have to manage this outside of the SpeedDial
