### ISSUE TITLE
Apply gradient on background overlay

### ISSUE THREAD

**Issue by Choem** [darioielardi/flutter_speed_dial#222]
I'm struggling with understanding how someone would apply a gradient on the background overlay, if it is even possible. Because when I take a look at the BackgroundOverlay class I see that that its root widget is a ColorFiltered widget.

![image](https://user-images.githubusercontent.com/10047984/145384327-18f3c5b0-f41e-4ce2-b16c-65da1dd30bed.png)

I would suggest changing this so that a gradient can be applied to the box decoration of the container instead of just a color.

Are there any plans on updating the BackgroundOverlay class?
If not I can add it and eventually open a PR.

**Comment by prateekmedia** [comment]
If you can make the speed Dial cutout even in the gradient then a PR is welcome.

Reason ColorFiltered is used is for the speed dial cutout in the overlay.

**Comment by luca-colazzo** [comment]
@Choem so, are you working on this?

**Comment by Choem** [comment]
Schedules have been changed and I currently don't have time to work on it. I'll reopen the issue if I have time and start working on it. Others feel free to reopen if you want to change this as well.
