### ISSUE TITLE
BackgroundOverlay stays after widget dispose.

### ISSUE THREAD

**Issue by uwumouse** [darioielardi/flutter_speed_dial#228]
I use 2 different FABs for my Scaffold. First one is used by default and the second one is showed when user enters edit mode by clicking a `SpeedDialChild` in the 1st FAB. These FABs both use Speed Dial.   
I check which FAB should be displayed with this logic:
```dart
floatingActionButton: _inEditMode
            ? EditFAB(
                ...
              )
            : ScheduleFAB(
                onEnterEditMode: () {
                  setState(() {
                    _inEditMode = true;
                  });
                },
              )
```

`ScheduleFAB` also uses an overlay, and when I tap on the `SpeedDialChild` that triggers `onEnterEditMode` everything works except the background overlay stays and I can't to anytning because of it. 

This is the `build` method in `ScheduleFAB`:
```dart
  @override
  Widget build(
    BuildContext context,
  ) {
    return SpeedDial(
      animatedIcon: AnimatedIcons.menu_close,
      openCloseDial: _isOpen,
      renderOverlay: false,
      spacing: 15,
      spaceBetweenChildren: 15,
      children: _getAdditionalButtons(),
    );
  }
```
And a `SpeedDialChild` that triggers modes swap:
```dart
SpeedDialChild(
  child: const Icon(Icons.edit),
  label: 'Редактировать',
  onTap: widget.onEnterEditMode
)
```

I really want to know how to fix this issue. Am I doing something wrong and is there another proper way of doing the thing I want?

Portion of `pubspec.yaml`:
```yaml
dependencies:
    flutter:
        sdk: flutter
    flutter_speed_dial: ^5.0.0+1
```

**Comment by Kindane** [comment]
nvm, use Java

**Comment by prateekmedia** [comment]
@Kindane What do you mean?

**Comment by luca-colazzo** [comment]
You have to close the FAB before replacing it, so the overlay gets disposed correctly
