### ISSUE TITLE
decoration not optimized with LTR 

### ISSUE THREAD

**Issue by Yasoury** [darioielardi/flutter_speed_dial#232]
I am using it as a drawer and its working fine when its from RTL
but when i change the local the label disappear and no padding around the child
![Screenshot_1647352727](https://user-images.githubusercontent.com/88273182/158394113-0b9df294-3a88-4174-992a-0cb9368a0870.png)
![Screenshot_1647352731](https://user-images.githubusercontent.com/88273182/158394121-192e7ae7-0001-49b5-a518-5b6c61471808.png)

**Comment by luca-colazzo** [comment]
From the README:

The SpeedDial widget is built to be placed in the `Scaffold.floatingActionButton` argument, replacing the `FloatingActionButton `widget. You can set its position using `Scaffold.floatingActionButtonLocation` argument. It can also be used with `Scaffold.bottomNavigationBar` and `Snackbar`.

`Drawer` is not included, so it's not supported. If you want to make it work there, any PR is welcome

**Comment by Yasoury** [comment]
I am using it as float button I can't make the LTR version make padding from the screen 
![Screenshot_1651263357](https://user-images.githubusercontent.com/88273182/166063342-e89a8156-b1ee-4f0a-aad7-3add116d6ee4.png)
![Screenshot_1651263362](https://user-images.githubusercontent.com/88273182/166063350-571b5f1d-aea1-4a00-93f3-6d88a864aee0.png)

**Comment by luca-colazzo** [comment]
share code?
