### ISSUE TITLE
default icon not change

### ISSUE THREAD

**Issue by Bugimz** [darioielardi/flutter_speed_dial#235]
` floatingActionButton: Obx(
        () => SpeedDial(
          icon: Icons.add,
          activeIcon: Icons.close,`

i try to change icon but not worked..
icon and activeicon not worked for me
for icon show bar
and activeicon close
i cant change them

**Comment by prateekmedia** [comment]
Screenshot?

**Comment by Bugimz** [comment]
> Video recording or Screenshot?


https://user-images.githubusercontent.com/101297316/161256307-7ee86915-b161-40ac-b9fe-0119f431aa32.mp4

**Comment by luca-colazzo** [comment]
Does it work outside of `Obx()`?

**Comment by Bugimz** [comment]
> Does it work outside of `Obx()`?

No, unfortunately it does not work

**Comment by prateekmedia** [comment]
Oh are you using animated icon? Please read https://github.com/darioielardi/flutter_speed_dial#types-of-child-for-speeddial-ordered-by-their-priority
