### ISSUE TITLE
A weird circle overlay  if using backgroundColor that have opacity < 100

### ISSUE THREAD

**Issue by haizadvnet** [darioielardi/flutter_speed_dial#241]
I got a weird circle overlay on the SpeedDial widget.

![Untitled](https://user-images.githubusercontent.com/85096754/161470570-953c5343-aa61-474f-984f-8bc3de96c6da.png)

**Current version  (have a weird circle overlay):**
1) Flutter 2.10.3 • channel stable
2) Dart 2.16.1
3) flutter_speed_dial pubspec.yaml (already tested on different package version, yet still got the same outcome)
    - flutter_speed_dial: ^3.0.5
    - flutter_speed_dial: ^4.1.0
    - flutter_speed_dial: ^5.1.0

**Previous version (no weird circle overlay):**
1) Flutter 2.2.3
2) Dart 2.13.4
3) flutter_speed_dial pubspec.yaml
    - flutter_speed_dial: ^3.0.5

Code: 
```
floatingActionButton: SpeedDial(
            // animatedIcon: AnimatedIcons.play_pause,
            icon: Icons.sms_rounded,
            animatedIconTheme: IconThemeData(size: 22),
            foregroundColor: Colors.white,
            backgroundColor: Colors.black45,
            visible: true,
            curve: Curves.bounceIn,
            children: [
              SpeedDialChild(
                child: Icon(FontAwesomeIcons....),
                foregroundColor: Colors.white,
                backgroundColor: Color(0xFF0088CC),
                onTap: () {
                },
                label: "B",
                labelStyle: TextStyle(
                    fontWeight: FontWeight.w500,
                    color: Colors.white,
                    fontSize: 16.0),
                labelBackgroundColor: Colors.black45,
              ),

              // FAB 1
              SpeedDialChild(
                  child: Icon(FontAwesomeIcons...),
                  foregroundColor: Colors.white,
                  backgroundColor: Color(0xFF25D366), //Colors.black45,
                  onTap: () {
                  },
                  label: "A",
                  labelStyle: TextStyle(
                      fontWeight: FontWeight.w500,
                      color: Colors.white,
                      fontSize: 16.0),
                  labelBackgroundColor: Colors.black45),
            ],
          ),
```

Update: 
I managed to handle the issue temporarily by changing the value of backgroundColor parameter into 100% opacity

//backgroundColor: Colors.black45,
backgroundColor: Colors.black,

**Comment by haizadvnet** [comment]
I am closing this issue right now, suspect relates with https://github.com/darioielardi/flutter_speed_dial/issues/218

**Comment by haizadvnet** [comment]
The issue has been resolved after I change the value of backgroundColor parameter into 100% opacity

```
//backgroundColor: Colors.black45,

backgroundColor: Colors.black,
```

**Comment by haizadvnet** [comment]
thank you for spending your time on debugging the issue. Do you plan to look into it?

**Comment by luca-colazzo** [comment]
He is saying that this issue doesn't depend on our package, but on the `FloatingActionButton` widget, that depends on flutter.
We can't fix that, you have to open an issue on [flutter/flutter](https://github.com/flutter/flutter/issues/)

**Comment by haizadvnet** [comment]
I managed to remove the overlay by adding elevation parameter on it and set the value to 0.0.
```
          floatingActionButton: SpeedDial(
            elevation: 0.0,
            icon: Icons.sms_rounded,
            animatedIconTheme: IconThemeData(size: 22),
            foregroundColor: Colors.white,
            backgroundColor: Colors.black45,
```

Reference : https://github.com/flutter/flutter/issues/20166
