### ISSUE TITLE
Flutter for web support

### ISSUE THREAD

**Issue by emersonsiega** [darioielardi/flutter_speed_dial#25]
Hello

I'm using flutter_speed_dial in my app and now I need to create a web version of some views and would be very nice if this package support Flutter Web :)

Are you thinking in add support for Flutter Web soon? This is in your plans?
Thanks!

**Comment by emersonsiega** [comment]
Looking at the sources, the only change needed is:
`import 'package:flutter/material.dart';`
for
`import 'package:flutter_web/material.dart';`

I'm using another packages where people create another branch (`web` for instance) and only change some things like I showed above.

**Comment by darioielardi** [comment]
It would be very nice to have a branch with a working web version, I will work on it for sure but I'm really busy these days so I can't assure anything about timing. If you want to do that by yourself PRs are always welcome :)

**Comment by prateekmedia** [comment]
It uses components provided by flutter material so I think it will be compatible with flutter Web I think?

**Comment by prateekmedia** [comment]
I am pinning this issue, but I think it is compatible with web already, ping me if I am wrong.
