### ISSUE TITLE
Using SpeedDial with custom view

### ISSUE THREAD

**Issue by thePlayer094** [darioielardi/flutter_speed_dial#254]
Is there any chance that i can use SpeedDial withouth FloationActionButton? Like this:

` 
Flexible(
                          flex: 1,
                          child: GestureDetector(
                            onTap: () {
                              logger.i("Open dial...");
                              isDialOpen.value = !isDialOpen.value;
                              _menuWidget.call();
                            },
                            child: Container(
                              decoration: BoxDecoration(
                                color: Colors.transparent,
                                borderRadius: BorderRadius.circular(100.0),
                                boxShadow: [
                                  BoxShadow(
                                    color: CustomColors.sideOrange
                                        .withOpacity(0.35),
                                    blurRadius: 7.0,
                                    spreadRadius: 0.0,
                                    offset: const Offset(
                                      0.0,
                                      3.0,
                                    ),
                                  ),
                                ],
                              ),
                              child:
                                  Stack(alignment: Alignment.center, children: [
                                Image.asset(
                                  "assets/icons/default_white_button.png",
                                  width: 75,
                                  height: 75,
                                ),
                                Image.asset(
                                  "assets/icons/menu_icon.png",
                                  width: 50,
                                  height: 40,
                                ),
                              ]),
                            ),
                          )),
`

And the menuWidget is: 

`
void _menuWidget() {
   SpeedDial(
      overlayColor: Colors.white,
      overlayOpacity: 0.2,
      openCloseDial: isDialOpen,
      children: [
        SpeedDialChild(child: Icon(Icons.map), label: "talk"),
        SpeedDialChild(child: Icon(Icons.mail), label: "Mail"),
        SpeedDialChild(child: Icon(Icons.message), label: "ASD"),
      ],
    );
  }
`

Thank you!

**Comment by prateekmedia** [comment]
Yes there is a dialRoot Widget for your first case, you can use it to assign new dial root Widget instead of floating action button.

**Comment by thePlayer094** [comment]
Dear prateek! I've tried this method but the result asnwer is: "type 'Container' is not a subtype of type '((BuildContext, bool, () => void) Widget)? 

What is the problem with my code, could you help me pls?

`Flexible(
                          flex: 1,
                          child: GestureDetector(
                            onTap: () {
                              isDialOpen.value = !isDialOpen.value;
                            },
                            child: SpeedDial(
                              overlayColor: Colors.white,
                              dialRoot: dialRoot(context, isDialOpen.value, (){}),
                              overlayOpacity: 0.2,
                              openCloseDial: isDialOpen,
                              children: [
                                SpeedDialChild(
                                    child: Icon(Icons.map), label: "Small talk"),
                                SpeedDialChild(
                                    child: Icon(Icons.mail), label: "Mail"),
                                SpeedDialChild(
                                    child: Icon(Icons.message), label: "Crushes"),
                              ],
                            ),
                          ),
                        )`

And the dialRoot:

`dialRoot(BuildContext context,  bool open, VoidCallback toggleChildren) => Container(
    decoration: BoxDecoration(
      color: Colors.transparent,
      borderRadius: BorderRadius.circular(100.0),
      boxShadow: [
        BoxShadow(
          color: CustomColors.atOrange.withOpacity(0.35),
          blurRadius: 7.0,
          spreadRadius: 0.0,
          offset: const Offset(
            0.0,
            3.0,
          ),
        ),
      ],
    ),
    child: Stack(alignment: Alignment.center, children: [
      Image.asset(
        "assets/icons/default_white_button.png",
        width: 75,
        height: 75,
      ),
      Image.asset(
        "assets/icons/menu_icon.png",
        width: 50,
        height: 40,
      ),
    ]),
  );`

**Comment by thePlayer094** [comment]
Thank you very much dear Prateek!
