### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by yegor-pelykh** [darioielardi/flutter_speed_dial#255]
Is it possible to make web support for your package?

**Comment by prateekmedia** [comment]
Doesn't it support web already?

**Comment by yegor-pelykh** [comment]
![1](https://user-images.githubusercontent.com/21262076/172663965-12339fe2-d8ff-4641-b31f-48c3d8a59884.png)

**Comment by prateekmedia** [comment]
Have you tried it on web?

**Comment by yegor-pelykh** [comment]
Now I've tried. And it seems to work. Wow!
Does anyone know why web support is not showing up in the platform information on the [pub.dev](https://pub.dev/packages/flutter_speed_dial)? I've seen many packages that are officially supported on the web, they have the 'web' among the platforms.

**Comment by prateekmedia** [comment]
@yegor-pelykh I have used dart:io for using *Platform.isIOS* but dart:io doesn't support web, so we either need to declare web as supported manually in pubspec or use universal_platform package instead of dart:io

**Comment by yegor-pelykh** [comment]
It would be nice, of course. But the main thing is that it works.
By the way, the package is cool, thanks for making it!

**Comment by prateekmedia** [comment]
Done!
