### ISSUE TITLE
Children are not centered if size is reduced

### ISSUE THREAD

**Issue by levydanqc** [darioielardi/flutter_speed_dial#261]
When reducing the children's sizes with `childrenButtonSize` it offsets them a little.

The smaller they are, the more offset to the left they are.

It should stay center no matter the size.
![screenshot](https://user-images.githubusercontent.com/58832530/174462322-84b3ee49-e361-464d-8647-3ae7de7826e5.png)

**Comment by luca-colazzo** [comment]
This is because if your FAB is aligned to the right, then the icons are. It's how FABs work

**Comment by luca-colazzo** [comment]
Closing as solved and inactive
