### ISSUE TITLE
Overlay stays on top after SpeedDialChild.onTap push Navigator

### ISSUE THREAD

**Issue by levydanqc** [darioielardi/flutter_speed_dial#262]
If the click on a SpeedDialChild is used to Navigate to another view, with

```
onTap: () => Navigator.push(
  context,
  MaterialPageRoute(
      builder: (context) =>
          const AnotherView()),
),
```

the **BackgroundOverlay** stays on and the view is unclickable.

**Comment by levydanqc** [comment]
I made some tests and if I add a `debugPrint('Open')` and `debugPrint('Close')` on the `onOpen` and `onClose` of **SpeedDial**:

1. Click on the SpeedDialChild to navigate to a new page
2. 'Close' is printed
3. The new view appear
4. 'Open' is printed 2 times
5. 'Open' is then printed each time I click anywhere

**Comment by levydanqc** [comment]
@luca-colazzo Please let me know if you know how to fix this

**Comment by DanielKirkwood** [comment]
I am having the same issue, background overlay remains after using `Navigator.pushNamed ` from within SpeedDialChild.

**Comment by luca-colazzo** [comment]
Will investigate next week

**Comment by hatemragab** [comment]
+1

**Comment by ppanuwatpr** [comment]
+1, Same issue, The overlay still remains after page change with `Get.to`.

**Comment by passerby-yyds** [comment]
![image](https://user-images.githubusercontent.com/21983345/187357453-12b57fea-9419-40bd-9b89-a9753dd6d39d.png)
https://github.com/darioielardi/flutter_speed_dial#how-to-use-openclosedial-property

**Comment by DzonaTheSymbol** [comment]
> 

This didn't do it for me. Still rendering overlay when navigating to a new screen.

**Comment by krmuller** [comment]
Set property `renderOverlay` to `false` solved my problem.
