### ISSUE TITLE
Is Material 3 Supported ? 

### ISSUE THREAD

**Issue by MehmetKaranlik** [darioielardi/flutter_speed_dial#263]
Like in the title is Material 3 supported? Unlike the full circle button, it comes with a rounded rectangle with a subtle corner radius.

**Comment by prateekmedia** [comment]
Actually Material 3 doesn't have Speed Dial (if you can find it please share the link), but you still can use this with Material 3 normally as you would use M3 in your app

**Comment by theo-j22** [comment]
https://m3.material.io/components/floating-action-button/specs#669a1be8-7271-48cb-a74d-dd502d73bda4

![image](https://user-images.githubusercontent.com/16556292/190890257-82afcd61-f249-45a2-bca0-7b603534ca66.png)
