### ISSUE TITLE
Overlay does not disappear when pushing a widget with useRootNavigator: false.

### ISSUE THREAD

**Issue by pavittarsingh315** [darioielardi/flutter_speed_dial#265]
So basically I have the following Widget:
```
Widget _dial(BuildContext context) {
    return SpeedDial(
      icon: Icons.shopping_cart,
      backgroundColor: Colors.blue,
      iconTheme: const IconThemeData(color: Colors.white),
      overlayOpacity: 0.5,
      children: [
        SpeedDialChild(
          backgroundColor: Colors.blue,
          child: GestureDetector(
            behavior: HitTestBehavior.translucent,
            onTap: () {
              showModalBottomSheet(
                context: context,
                useRootNavigator: false,
                builder: (_) => Container(color: Colors.red),
              );
            },
            child: const Icon(Icons.attach_money_rounded, color: Colors.white),
          ),
        ),
      ],
    );
  }
```

**The issue is**, when I tap the dial child, the modal opens, however the overlay of the `SpeedDial` widget is covering the modal. The `SpeedDial` is also not closed when I tap the dial child.

I know that the `SpeedDialChild` widget has an `onTap` field which I could implement the `showModalBottomSheet` function however this is widget is a simple example. In reality, I am using a third party widget which I am setting as the child of the `SpeedDialChild`. That third party widget has a built in `GestureDetector` which I can do nothing about.

Is there a way I can manually dismiss the overlay/close the `SpeedDial`? I have tried `Navigator.pop(context)` however that doesn't close the dial.

Thank you!

**Comment by pavittarsingh315** [comment]
I believe this is similar to issue [$262](https://github.com/darioielardi/flutter_speed_dial/issues/262)

**Comment by luca-colazzo** [comment]
dupe #262
