### ISSUE TITLE
How to remove boxshadow from SpeedDialChild

### ISSUE THREAD

**Issue by ziqq** [darioielardi/flutter_speed_dial#266]
How to remove boxshadow from SpeedDialChild, labelShadow set empty list is not working.

![image](https://user-images.githubusercontent.com/20646071/176180325-0daa90d3-79fd-4dce-a66d-7d338dc9f71e.png)

`SpeedDialChild(
    labelShadow: [],
    child: Container(
      padding: const EdgeInsets.all(12),
      child: SvgPicture.asset(
        'assets/icons/client_add.svg',
        color: Colors.white,
      ),
    ),
    label: 'Добавить клиента',
    foregroundColor: Colors.white,
    backgroundColor: Theme.of(context).colorScheme.secondary,
    labelBackgroundColor: BBUiKitTheme.barrierColor,
    labelStyle: TextStyle(
      height: 1.1,
      fontSize: 13,
      color: Colors.white,
    ),
    onTap: () => showCupertinoModalBottomSheet(
      context: context,
      builder: (context) => ClientActionView(),
    ),
)`

**Comment by DzonaTheSymbol** [comment]
@ziqq I'm not sure to what the screenshot is pointing to, but I believe that what you need is the `elevation` property.

i.e.
![image](https://user-images.githubusercontent.com/104906580/185068776-49514210-950e-43ce-b0bc-57a1d90f6854.png)

**Comment by prateekmedia** [comment]
@ziqq I hope the issue is fixed as told by @DzonaTheSymbol, you can set the elevation property to 0 for SpeedDialChild
