### ISSUE TITLE
request function: flare compatible or manual control

### ISSUE THREAD

**Issue by nitneuq33** [darioielardi/flutter_speed_dial#27]
Hello, I try to customize the main speed dial by using flare animation, I try to hide animated icon by stack my flare but I can't open or close speed dial with external interaction like inkwell. I think external control is more easy that flare interaction. Thank you

**Comment by prateekmedia** [comment]
Use openCloseDial property of latest v2, assign it a valuenotifier and update it to hide or show the Speed dial, false for hide and true for show.
