### ISSUE TITLE
Possible calling twice to overlayEntry?.remove()

### ISSUE THREAD

**Issue by javierdvalle** [darioielardi/flutter_speed_dial#277]
I have a simple app with a login screen and a home screen. I am using the SpeedDial widget in the home screen. Whenever I use the SpeedDial, and then try to go back to the login screen, I get this exception error:

```
Exception has occurred.
_AssertionError ('package:flutter/src/widgets/overlay.dart': Failed assertion: line 161 pos 12: '_overlay != null': is not true.)
```

Steps to reproduce:

0. log in and open the home screen
1. tap on SpeedDial
2. close SpeedDial
3. go to the previous screen in the stack (by calling Navigation.pop())
4. Exception is raised

What I found: there are two calls to the method `overlayEntry?.remove()` that are being executed: the first is in the `toggleOverlay()` method, and it is executed when closing the SpeedDial (step2). The second is in the `dispose()` method, and it is executed when the SpeedDial is destroyed by `Navigation.pop()` (step3). This second call fails because the `_overlay` internal variable was already set to null by the first call. 

I commented out the `overlayEntry?.remove()` from the `dispose()` method and the error is gone, but i'm not sure if this may cause any side-effects.

**Comment by prateekmedia** [comment]
Can you try this git version and see it the issue persists?

**Comment by javierdvalle** [comment]
The error is gone, thanks!!
