### ISSUE TITLE
Make label clickable

### ISSUE THREAD

**Issue by James-A-White** [darioielardi/flutter_speed_dial#28]
As I watch user interact with our app, I notice that some of them (especially those on iOS) often click on the label instead of the button. Is it possible to include a flag that will allow the label to also respond to click events?

Thanks for the great component!

**Comment by sepranashari** [comment]
I need this too.

**Comment by Yassine-ala** [comment]
Any updates or workaround on this feature please ?

**Comment by Allen-Hu** [comment]
Kinda late, but you could specify your own `labelWidget`, in this case I use an `InkWell` wrapped in a `Card`.
```
labelWidget: Card(
  clipBehavior: Clip.antiAliasWithSaveLayer,
  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
  child: InkWell(
    child: Padding(
      padding: const EdgeInsets.all(8.0),
      child: Text("label text"),
    ),
    onTap: () {},
  ),
)
```

**Comment by prateekmedia** [comment]
It's already their, just specify onTap property, your label will be lockable, if you mean label widget then you need to wait for #59 to merge
