### ISSUE TITLE
Dears @prateekmedia @luca-colazzo ,

### ISSUE THREAD

**Issue by tarekmabdallah91** [darioielardi/flutter_speed_dial#284]
Dears @prateekmedia @luca-colazzo , 
please your support, I faced this issue when showing the floating action in RTL, using v 6.2.0, 
tried v 5.1.0  and found the same issue.

when set `switchLabelPosition` and locate at `FloatingActionButtonLocation.endFloat`

![image](https://user-images.githubusercontent.com/56560184/201028682-466f41fb-a713-4079-be24-4c68bbda01db.png)

_Originally posted by @tarekmabdallah91 in https://github.com/darioielardi/flutter_speed_dial/issues/199#issuecomment-1309883978_

**Comment by luca-colazzo** [comment]
dupe #199
