### ISSUE TITLE
gradient color is not changing when FAB is not active. 

### ISSUE THREAD

**Issue by iamkartiknayak** [darioielardi/flutter_speed_dial#291]
**The following code adds the linear gradient when FAB is active otherwise defaults to blue color.**

        `floatingActionButton: SpeedDial(
        icon: FeatherIcons.plus,
        activeIcon: FeatherIcons.x,
        gradient: kButtonGradient,

        gradientBoxShape: BoxShape.circle,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.all(
            Radius.circular(100),
          ),
        ),
        // animatedIcon: AnimatedIcons.add_event,
        animationDuration: Duration(milliseconds: 800),
        childPadding: EdgeInsets.only(bottom: 10.0),
        child: Icon(FeatherIcons.plus),
        // overlayColor: kPrimaryAccent,
        // overlayColor: Colors.black.withOpacity(0.5),
        // overlayOpacity: 0.9,
        children: [...]`

**Comment by prateekmedia** [comment]
Can you elaborate more?

**Comment by iamkartiknayak** [comment]
After stopping the debugging and restarting the application it got fixed. Sorry I couldn't update the issue. It so happened that FAB didn't have the gradient color when it was inactive even after doing hot restart so many times.
