### ISSUE TITLE
How can I open the menu programmatically?

### ISSUE THREAD

**Issue by joseangeljimenez** [darioielardi/flutter_speed_dial#30]
I'd like to open the menu programmatically when the user interacts with a different widget.
Is there a way to do so?

This shows a "generic" way to send a tap to a Widget, however, I cannot set a key when creating a SpeeDial,
https://stackoverflow.com/a/50962382/634355

Thanks for you great work!

**Comment by shizambles** [comment]
I have pull request that achieves this - https://github.com/darioielardi/flutter_speed_dial/pull/45

**Comment by dspoeri** [comment]
I'd find this feature very useful as well. In my use case, I want to keep the SpeedDial open in SOME cases, so I set `closeManually` to `true`, but want to close it depending on different actions.
Just tried it out with the PR of @shizambles - works fine for me.

**Comment by adg-mh** [comment]
I need this as well. @darioielardi can you say whether this will accepted?

**Comment by prateekmedia** [comment]
Checkout V2 #90 it will be merged soon, it has openCloseDial Property.
