### ISSUE TITLE
centerdocked behavior

### ISSUE THREAD

**Issue by hbdejesus** [darioielardi/flutter_speed_dial#31]
When there's no `floatingActionButtonLocation: ` in the scaffold, the SpeedDial is fine.
![Screen Shot 2019-08-20 at 3 12 29 PM](https://user-images.githubusercontent.com/32647349/63325758-5b246f00-c35d-11e9-9aac-d5f46ce40a15.png)

But when it is set to `floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,` it is placed in the bottom right of the screen. 
![Screen Shot 2019-08-20 at 3 11 58 PM](https://user-images.githubusercontent.com/32647349/63325861-8f982b00-c35d-11e9-88ce-0720684b186a.png)

How can I place the speed dial to the center of bottomnavbar?

**Comment by darioielardi** [comment]
It's not possible to set the `SpeedDial` position with the `Scaffold.floatingActionButtonLocation` argument, but it's possible to set right/bottom margin with the `marginRight` and `marginBottom` arguments (default to `16`) to place the button anywhere in the screen.

**Comment by fabioselau077** [comment]
Same problem...

**Comment by matiascoar** [comment]
I got this by using
```
        marginRight: ( MediaQuery.of(context).size.width - [buttonSize] ) / 2 ,

```
but if would be nice to have a less archaic way of doing something like this :)

**Comment by ollydixon** [comment]
@matiascoar has click problems if you do this.

**Comment by prateekmedia** [comment]
Let's discuss it their #75
