### ISSUE TITLE
Paginate or scroll speedchilds

### ISSUE THREAD

**Issue by kaiquegazola** [darioielardi/flutter_speed_dial#35]
It would be nice if could scroll/paginate the speedchilds, as on small screens with the default settings there is no way to put more than 4 items.

**Comment by darioielardi** [comment]
Sounds interesting, would you mind share some prototype/example gif?

**Comment by loomp** [comment]
I can imagine wrapping buttons with a ListView should do the trick.

**Comment by Anvin-HSS** [comment]
Any solution for scroll/paginate the speedchilds?

**Comment by prateekmedia** [comment]
Let's discuss it there #69
