### ISSUE TITLE
Implementation of the onTap option

### ISSUE THREAD

**Issue by smartlightning** [darioielardi/flutter_speed_dial#37]
I have issues trying to understand, how I can add the Navigator.pushNamed(context, RoutePaths.#routetonavigateto) and thereby reference the page I want to open. OnTap of the option I want to open a new window in my app. This is easy with just the simple FloatingActionButton, as it has the onPressed(){} option, however, it seems SpeedDialer doesn't support this. 
Any help would be much appreciated!
Thanks, Chris

**Comment by prateekmedia** [comment]
I think you should try the onOpen parameter if you want the whole speed dial to behave like a fab, if you are talking about its children's then you should try onTap property of their.
