### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by sudoFerraz** [darioielardi/flutter_speed_dial#38]
Currently I need to use ref: master on my pubspec.yaml instead of pointing to the current release, as I need the labelWidget: from AnimatedChild to take out the shadows from the label.
This is not best practice and our app is in production, if you need help maintaining the repo I can gladly help to publish it and keep track of latest releases and changeLog.

Great job btw, I appreciate it
😄

**Comment by darioielardi** [comment]
I'm sorry, I haven't had much time last months to dedicate to this project, I'd be happy to receive any contribution.
Anyway, I've just published a new, updated version!

**Comment by shinayser** [comment]
The latest version has a bug on the animation of the labels. Its kinda weird. Please take a look!

**Comment by darioielardi** [comment]
The bug is fixed, thanks for letting me know. The `labelWidget` now completely replaces the label, to let the user customize it entirely.
