### ISSUE TITLE
With LabelWidget, also label is required

### ISSUE THREAD

**Issue by dekadevelop** [darioielardi/flutter_speed_dial#41]
If we implement our own labelWidget, we need to set the label otherwise an exception occours

label: 'ignored',
labelWidget: SpeedDialLabel('Delete', 60),

**Comment by darioielardi** [comment]
I can't reproduce your case, seems like this shouldn't happen at all. Are you sure you're using the last version? Can you share some code to better understand?
Thanks.

**Comment by darioielardi** [comment]
Sorry you're right, last commit fixes this. Thank you for reporting.
