### ISSUE TITLE
System back doesnt close opened speed dial

### ISSUE THREAD

**Issue by Stewioie** [darioielardi/flutter_speed_dial#42]
open a dial press hardware back button
Screen popped away

It should close dial first

**Comment by darioielardi** [comment]
That's definitely something I'd like to achieve, I'll work on it in the near future.

**Comment by avinashyalgonde** [comment]
Is there any solution found for this? In our application we want to display logout dialog with Yes and No option. But as dial is not closed I am facing some issues.

**Comment by prateekmedia** [comment]
> Is there any solution found for this? In our application we want to display logout dialog with Yes and No option. But as dial is not closed I am facing some issues.

Yep you can checkout my fork, it already has this feature
https://github.com/prateekmedia/flutter_speed_dial#close-on-willpop

**Comment by prateekmedia** [comment]
Checkout v2 and the instructions here https://github.com/darioielardi/flutter_speed_dial#close-on-willpop, to make it work.


If it persists ask me to reopen this.
