### ISSUE TITLE
Label Text Right position

### ISSUE THREAD

**Issue by MarceloRab** [darioielardi/flutter_speed_dial#43]
For a button on the left side of the screen, how do we move the SpeedDialChild texts to the right?

For now it's like this.

```dart
labelWidget: Transform.translate(
   offset: Offset(120, 0),
   child: Text(
     "test 1",
     style: ConsultaAppTheme.titleDefault,
   ),
),
```

**Comment by prateekmedia** [comment]
What do you mean by it? Use cases? Share you code more to add this.

**Comment by prateekmedia** [comment]
Checkout [new branch](https://github.com/darioielardi/flutter_speed_dial/tree/new), it has everything fixed.
