### ISSUE TITLE
Label shadow issue

### ISSUE THREAD

**Issue by mamayadi** [darioielardi/flutter_speed_dial#46]
I cannot modify the shadow of the label here is the exemple:
![image](https://user-images.githubusercontent.com/28813940/70431985-7b984680-1a7e-11ea-84f5-018ebc32351a.png)

**Comment by darioielardi** [comment]
Unfortunately it's not possible to customize the default label shadow, but you can always provide your own label widget completely custom. Just use the labelWidget argument of the SpeedDialChild!

Let me know if I can close!

**Comment by prateekmedia** [comment]
Checkout [new branch](https://github.com/darioielardi/flutter_speed_dial/tree/new), it has everything fixed.
