### ISSUE TITLE
Floating Snackbar will not appear with SpeedDial

### ISSUE THREAD

**Issue by nilsreichardt** [darioielardi/flutter_speed_dial#47]
If you set the behavior of a snackbar to `floating`, no more snackbars will be displayed on the entire page. With a normal FloatingActionButton it will work.

### How to repduce
```
import 'package:flutter/material.dart';
import 'package:flutter_speed_dial/flutter_speed_dial.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
          snackBarTheme:
              SnackBarThemeData(behavior: SnackBarBehavior.floating)),
      home: Scaffold(
        appBar: AppBar(title: Text("Flutter Demo")),
        body: Center(child: Text('Center')),
        floatingActionButton: Builder(
          builder: (context) => SpeedDial(
            onPress: () => Scaffold.of(context)
                .showSnackBar(SnackBar(content: Text("Text"))),
            child: Icon(Icons.add),
          ),
        ),
      ),
    );
  }
}
```

**Comment by dspoeri** [comment]
Got the same bug ...

**Comment by Rosco89** [comment]
Any updates, or solution?

**Comment by bhargavcp** [comment]
Any updates on this issue?

**Comment by prateekmedia** [comment]
Checkout [new branch](https://github.com/darioielardi/flutter_speed_dial/tree/new), it has everything fixed.

**Comment by ccadieux** [comment]
@prateekmedia 
I checked out the new branch. Was able to use it with my current code with no changes. I think the example app needs some love on that branch though. I needed to comment some stuff out to use it. Also was complaining about flutter embedded.

Seems close to ready. I would make a new release of it with a major version and be clear it's a potential breaking change. 

Great work.
