### ISSUE TITLE
Conditional Speed Child

### ISSUE THREAD

**Issue by max202021** [darioielardi/flutter_speed_dial#49]
I have 3 speed child element. One of the element needs to be shown only if certain condition is met. 
I have used ternary operator and  if condition is not met then used container. It failed.

How can we implement conditional Speed child?

**Comment by Elviron** [comment]
In the children list, just do `condition == true ? SpeedDialChild() : SpeedDialChild(backgroundColor: Colors.transparent, elevation: 0)`.
But then you have to have to conditional child at the top, i.e. that child should be last in the list.

**Comment by prateekmedia** [comment]
You can do what @Elviron said , also note that the error is cause by Container() as SpeedDial() does not except any other thing than SpeedDialChild(), so replace your Container with that.
