### ISSUE TITLE
 Background overlay does not cover BottomNavigationBar

### ISSUE THREAD

**Issue by kinex** [darioielardi/flutter_speed_dial#5]
Steps to reproduce:

1. Implement a view with BottomNavigationBar and SpeedDial
2. Tap SpeedDial

Expected result: 
Background overlay should be fullscreen

Actual result:
BottomNavigationBar is not covered by overlay and it is still accessible

**Comment by darioielardi** [comment]
In my mind it was supposed to work so, but it might be interesting to have a param to make the overlay cover the bottom bar ( maybe with ModalBarrier as you suggested ). I could work on that one of these days, if you want/need it before you could submit a PR :)

**Comment by kinex** [comment]
I don't know what possible guidelines say about this, but in my opinion it is more logical that the overlay is fullscreen similarly as with e.g. standard Flutter dialogs. Why would user like to switch tabs while the SpeedDial is open..? In my opinion it also looks better if it's fullscreen. This is only a cosmetic issue after all, so not any hurry to fix it :)

**Comment by tp** [comment]
Also surprised where the `-16` bottom padding come from / why that usually works.

In a project we draw the bottom bar manually (for animations that don't fit into the scaffold), which make the overlay a few pixels off.

**Comment by prateekmedia** [comment]
Let's discuss it their in #70

**Comment by kinex** [comment]
It seems we have discussed about this for 3 years soon :)

Issue is not only with `BottomNavigationBar`. I implemented a tablet layout (landscape) where I put `Drawer` and `Scaffold` on the same `Row` (the drawer is always visible on left edge). Now the background overlay covers only `Scaffold` and not the `Drawer`. As a workaround I had to disable the overlay totally.

**Comment by prateekmedia** [comment]
> It seems we have discussed about this for 3 years soon :)

Will look into it, fellow developers of flutter_speed_dial_material_design have already implemented it but they miss the core features like overlay and other stuff. will see how it goes...
