### ISSUE TITLE
Setting main button size

### ISSUE THREAD

**Issue by hazzo** [darioielardi/flutter_speed_dial#50]
Hello, thanks for the widget it's really cool.

I was wondering if there is actually a way of changing the size of the main button. If so how can be done? I didn't found anything in the docs neither in the issue tracker.

Thanks!

**Comment by richardbonneau** [comment]
I am also looking for the answer to this. I tried wrapping it in a container and setting the width and height of that container, as you can usually do with FABs, but it didn't work :(

**Comment by hazzo** [comment]
I’ve finally coded my own implementation that even snaps to fab positions of the material scaffold. If I found some time I’ll make a package of it and with the possibility to change the size of the main button.

**Comment by Rift3000** [comment]
> I’ve finally coded my own implementation that even snaps to fab positions of the material scaffold. If I found some time I’ll make a package of it and with the possibility to change the size of the main button.

I hope you turn it into a package, I would greatly appreciate it. I would rather not make my own custom implementation but if I have no other choice then so be it...

**Comment by hazzo** [comment]
> > I’ve finally coded my own implementation that even snaps to fab positions of the material scaffold. If I found some time I’ll make a package of it and with the possibility to change the size of the main button.
> 
> I hope you turn it into a package, I would greatly appreciate it. I would rather not make my own custom implementation but if I have no other choice then so be it...

I'll try to make some time this weekend to create the package, even there are things to improve but I would be good to have a starting point and grow through contribution.

**Comment by mzafer** [comment]
Hi Hazzo,

Are you able to share your implementation, if not ready as a package even as a gist will help.

Thanks

**Comment by prateekmedia** [comment]
Checkout V2 #90 it will be merged soon
