### ISSUE TITLE
Unable to toggle speed dial upon own label widget tap

### ISSUE THREAD

**Issue by loomp** [darioielardi/flutter_speed_dial#52]
It is impossible to toggle the speed dial menu when own label widget is tapped.
Function _toggleChildren is private.

A workaround is to rebuild the tree, but I guess it shall not be the option.
Alternatively, live with no gesture recognition on own labels.

I propose to instead of making toggleChildren function public, wrap GestureDetection with onTap function when labelWidget is passed.

**Comment by prateekmedia** [comment]
Check V2 it has this feature.
