### ISSUE TITLE
speed dial + bottom app bar = BOOM!

### ISSUE THREAD

**Issue by VadimOsovsky** [darioielardi/flutter_speed_dial#55]
![IMG_47AF9C0B36EB-1](https://user-images.githubusercontent.com/39897981/72444997-1264cb00-37c2-11ea-8201-26ad89becd2c.jpeg)

```
BottomAppBar(shape: CircularNotchedRectangle())
```
```
floatingActionButtonLocation: FloatingActionButtonLocation.endDocked,
```

**Comment by marciocesarcorrea** [comment]
The same thing happens to me

**Comment by marciocesarcorrea** [comment]
The same thing happens to me

**Comment by JohnPinto** [comment]
Same problem as well :cry:

**Comment by prateekmedia** [comment]
Duplicate of #75 let's discuss this their
