### ISSUE TITLE
SpeedDialChild shape is ignored

### ISSUE THREAD

**Issue by KhatibFX** [darioielardi/flutter_speed_dial#58]
![Screenshot_1584258931](https://user-images.githubusercontent.com/5616640/76697711-6bbf7c80-66d5-11ea-91da-0ec57caf1283.png)
Hi! I am running into an issue where the children of speed dial are ignoring the shape parameter provided, although the speed dial itself is rendering its shape normally. Here is a minimum example that shows this:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_speed_dial/flutter_speed_dial.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: SpeedDial(
        animatedIcon: AnimatedIcons.menu_close,
        animatedIconTheme: const IconThemeData(size: 22.0),
        closeManually: true,
        curve: Curves.bounceIn,
        tooltip: 'Toggle options',
        backgroundColor: Colors.black,
        foregroundColor: Colors.white,
        elevation: 8.0,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
        children: [
          SpeedDialChild(
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(10)),
              child: Icon(Icons.accessibility),
              foregroundColor: Colors.white,
              backgroundColor: Colors.black,
              onTap: () => print('FIRST CHILD')),
        ],
      ),
    );
  }
}
```

**Comment by m0veax** [comment]
Hi,

we have the same Error in our Project.

Could it be, that the Problem exists here:

https://github.com/darioielardi/flutter_speed_dial/blob/master/lib/src/animated_floating_button.dart#L25

**Comment by m0veax** [comment]
I wrote a quick fix above. It works for me, would you like to test it?

**Comment by prateekmedia** [comment]
Hey, you can checkout my fork, it already has this feature
https://github.com/prateekmedia/flutter_speed_dial

**Comment by m0veax** [comment]
Maybe you give some credit too :)

**Comment by prateekmedia** [comment]
> I wrote a quick fix above. It works for me, would you like to test it?



> Maybe you give some credit too :)

Already Given
https://github.com/prateekmedia/flutter_speed_dial/commit/fd1ae441bb7b1b9e0888a60cbd2cb4ba66bdd189

I am just assembling some good PR's and fixing some issues in them so that they can work perfectly all together

**Comment by m0veax** [comment]
Oh sry, that looked somehow different in the mail notifications :)

Just lets behave like I never wrote that.

Have a good day ✌️

**Comment by m0veax** [comment]
Do you plan to actively maintain the package?

Maybe we can share the maintainership by using an organization and give the package a new name.

I'm using it in several apps and don't want it to die.

On the other way, I don't have enough time to maintain it alone

**Comment by prateekmedia** [comment]
> Do you plan to actively maintain the package?
> 
> Maybe we can share the maintainership by using an organization and give the package a new name.
> 
> I'm using it in several apps and don't want it to die.
> 
> On the other way, I don't have enough time to maintain it alone

Yep, I am planning to maintain it as this is missing crucial features that should be present in it and also the pull requests are pending.

**Comment by m0veax** [comment]
Nice, I'm watching the repo and will help out on issues if I find some time.

I will change my dependencies if I have to touch my apps the next time.

**Comment by prateekmedia** [comment]
Checkout #90 i.e. V2 if it persists then reopen the issue.
