### ISSUE TITLE
Integration tests cannot tap button

### ISSUE THREAD

**Issue by huulbaek** [darioielardi/flutter_speed_dial#63]
Somehow it is not possible to tap the button using Flutter driver in tests. Everything works fine when not running the tests. And the tests also works with FloatingActionButton.

Example:

```dart
await driver.waitFor(find.byType('SpeedDial')); // This succeeds
await driver.tap(find.byType('SpeedDial')); // This times out
```

If I tap the button and open the children then the driver.tap succeed.

I think it may be related to this: https://github.com/flutter/flutter/issues/41937

Any ideas for a workaround?

**Comment by huulbaek** [comment]
My workaround is passing a string Key to SpeedDial and then using that in ```FloatingActionButton```

**Comment by prateekmedia** [comment]
Now you can specify key directly to SpeedDial
