### ISSUE TITLE
Label font color in dark mode

### ISSUE THREAD

**Issue by marcjoha** [darioielardi/flutter_speed_dial#64]
My app let the user switch between the default light and dark theme. When using the latter, the labels are same color as the background and hence unreadable. Needed to explicitly set the color with `labelStyle: TextStyle(color: Colors.black)` to make the labels visible in both themes.

**Comment by prateekmedia** [comment]
That's the required behaviour, if you doesn't want to specify the label color then we have to specify own label colour by default and I dont think that's what you want in your theme, as it might not match your theme and requirement
