### ISSUE TITLE
Weird gray box offset when opened

### ISSUE THREAD

**Issue by MathiasYde** [darioielardi/flutter_speed_dial#65]
Images should speak for themselves, but there are some issues with the shadow and the background gray background when opened

![image](https://user-images.githubusercontent.com/35201354/83330887-7def9680-a292-11ea-9e46-3bf5bcd7cd6e.png)

![image](https://user-images.githubusercontent.com/35201354/83330896-86e06800-a292-11ea-825e-2de64715da80.png)

**Comment by prateekmedia** [comment]
Checkout [new branch](https://github.com/darioielardi/flutter_speed_dial/tree/new), it has everything fixed.
