### ISSUE TITLE
Can't change the shape of the button to a wide rectangle

### ISSUE THREAD

**Issue by nausharipov** [darioielardi/flutter_speed_dial#68]
I need a wide rectangle like this:
![2020-06-24 12 26 20](https://user-images.githubusercontent.com/31556582/85508494-ffc6ab80-b615-11ea-905c-8d1bfb20d8ee.jpg)

I tried using 
shape: RoundedRectangleBorder(side: BorderSide(width: 10))
but it only affects the border, not the shape itself.

Is there a way to make a wide rectangle with icon and text inside?

**Comment by aman-ankit-51** [comment]
I want to achieve the same thing but have not been able to figure out.

**Comment by prateekmedia** [comment]
Checkout V2 #90 it will be merged soon, use the label and activeLabel property to do this.
