### ISSUE TITLE
Cant scroll the speed dial 

### ISSUE THREAD

**Issue by developerflutter** [darioielardi/flutter_speed_dial#69]
Speed dial can't be scrollable

**Comment by developerflutter** [comment]
Any update on this issue?

**Comment by Uros-V** [comment]
Well if you need to scroll it then you most probably aren't following Material Design guidelines.
Speed dial should contain at least 3 options and at most 6 options. 
Hence why I doubt scrolling will be implemented.
[https://material.io/components/buttons-floating-action-button#types-of-transitions](https://material.io/components/buttons-floating-action-button#types-of-transitions)
![image](https://user-images.githubusercontent.com/38900804/88903374-e4be0b80-d253-11ea-9189-f5ed4ed2a1f5.png)

**Comment by ZikBurns** [comment]
It would be good to have the option. I just checked how it looks in my app when I flip the screen and I cannot see some of the buttons in the top.

![Screenshot_2020-12-07-22-34-15-458_com example flutter_firestore](https://user-images.githubusercontent.com/45241208/101408340-91805780-38dc-11eb-8dd1-43f429fba965.jpg)

**Comment by prateekmedia** [comment]
You can try setting SpeedDialDirection in v4 to SpeedDialDirection.Left or Right based on the position of the speed dial for landscape mode, this way you can more dials.

**Comment by luca-colazzo** [comment]
Following material design, SpeedDial is not to be scrollable, so this won't be implemented.
If you want to implement that, feel free to open a PR

**Comment by MiniSuperDev** [comment]
@luca-colazzo Hi, you should allow it to be scrollable, for example in my app I only have 3 items, but it is used in Windows and Android with resizable screen, so the user can make the screen so small that only 1 item is seen, and cause it is not scrollable, it can't see the options

**Comment by prateekmedia** [comment]
@MiniSuperDev please refer to my comment for user who do less screen height. Also scrollable is not an option

**Comment by scopendo** [comment]
> You can try setting SpeedDialDirection in v4 to SpeedDialDirection.Left or Right based on the position of the speed dial for landscape mode, this way you can more dials.

I didn't find that this helped as the labels cause about the same or even less room than with the default direction of SpeedDialDirection.up.
