### ISSUE TITLE
overlay full screen

### ISSUE THREAD

**Issue by ghost** [darioielardi/flutter_speed_dial#70]
If `bottomNavigationBar` exists`overlay` cannot be full screen

**Comment by agnesjang98** [comment]
Bumping this, I'm having the same issue!

**Comment by lihaotian0607** [comment]
> Bumping this, I'm having the same issue!

waiting for the author to reply...

**Comment by devtronic** [comment]
This two lines are the problem: https://github.com/darioielardi/flutter_speed_dial/blob/2ef2c44f22b3452b38352d80cbd133dcf3e30682/lib/src/speed_dial.dart#L179-L180

**Comment by prateekmedia** [comment]
> These two lines are the problem:
> 
> https://github.com/darioielardi/flutter_speed_dial/blob/2ef2c44f22b3452b38352d80cbd133dcf3e30682/lib/src/speed_dial.dart#L179-L180

So, will removing these lines fix the problem?

**Comment by prateekmedia** [comment]
Checkout [new branch](https://github.com/darioielardi/flutter_speed_dial/tree/new), it has everything fixed.
