### ISSUE TITLE
Request: alternative base icon for closed SpeedDial

### ISSUE THREAD

**Issue by mikewillems** [darioielardi/flutter_speed_dial#72]
My use cases require alternative icons to the hamburger menu for the unopened Speed Dial. 

Couldn't find where in the code the icon for the base / closed dial is even specified, else would change. Happy to make the mod myself and submit PR if you let me know where in the code it's specified.

Thanks for a beautiful widget!

**Comment by Albert221** [comment]
It's the `animatedIcon` parameter that sets the icon on the speed dial. The package itself manages its animation, but you're free to provide any `AnimatedIcon` you like. [Here](https://www.youtube.com/watch?v=pJcbh8pbvJs) you can find Flutter-provided animated icons, but you can always create your own :)

**Comment by mikewillems** [comment]
Thanks for the quick response! AnimatedIcon adjusts only the icon that it
transforms to, no? I want to adjust the icon at rest - ie start from an
Icons.add not an Icons.menu.

**Comment by Albert221** [comment]
I welcome you to doing a little bit of research on your own :) The video under the link I gave you explains what are animated icons. Those are SVG images in three states, first, last, and the between. So the whole, for example, `menu_close` animated icon animates from `menu` to `close` icon.

There is no `add_close` animated icon from what I can tell. [Here](https://api.flutter.dev/flutter/material/AnimatedIcons-class.html) you can find all the icons that Flutter provides out-of-the-box.

**Comment by mikewillems** [comment]
Thanks for the tip! I was actually seeking something akin to the rotating_add_icon branch. 

Ftr, had done plenty of research prior - nature of the beast (especially with a platform that has as many abstractions and as much syntactic sugar as Flutter) is that you don't know what you don't know. I appreciate you guiding my search.
