### ISSUE TITLE
SpeedDial doesn't get docked with bottomAppBar properly.

### ISSUE THREAD

**Issue by mrmayurgithub** [darioielardi/flutter_speed_dial#75]
I am trying to use the statement ` floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,`  and every other statement of this type. But the **speedDial doesn't get docked at the proper position** where it should be.

**Comment by muhammadidrees** [comment]
Having the same issue. @mrmayurgithub did you find any solution to this?

**Comment by mrmayurgithub** [comment]
> 
> 
> Having the same issue. @mrmayurgithub did you find any solution to this?

No, there was a question asked on stackoverflow, but that didn't helped.

**Comment by muhammadidrees** [comment]
I ended up creating my own speed dial floating action button here is the code if you still need the functionality

``` dart
import 'package:flutter/material.dart';
import 'dart:math' as math;

import 'package:flutter_speed_dial/flutter_speed_dial.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  State createState() => new MyHomePageState();
}

class MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {
  AnimationController _controller;
  int _bottomNavIndex = 0;

  static const List<IconData> icons = const [
    Icons.person,
    Icons.person,
    Icons.person,
    Icons.person
  ];

  @override
  void initState() {
    super.initState();
    _controller = new AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 500),
    );
  }

  Widget build(BuildContext context) {
    Color backgroundColor = Theme.of(context).cardColor;
    Color foregroundColor = Theme.of(context).accentColor;
    return new Scaffold(
      backgroundColor: Colors.green[50],
      appBar: new AppBar(title: new Text('Speed Dial Example')),
      bottomNavigationBar: BottomAppBar(
        shape: CircularNotchedRectangle(),
        notchMargin: 8.0,
        child: Container(
          height: 60.0,
        ),
      ),
      floatingActionButton: Stack(
        overflow: Overflow.visible,
        alignment: Alignment.center,
        children: List<Widget>.generate(4, (int index) {
          Widget child = new Container(
            decoration: BoxDecoration(
              shape: BoxShape.circle,
            ),
            alignment: FractionalOffset.topCenter,
            child: new ScaleTransition(
              scale: new CurvedAnimation(
                parent: _controller,
                curve: new Interval(0.0, 1.0 - index / icons.length / 2.0,
                    curve: Curves.easeOut),
              ),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  FloatingActionButton(
                    heroTag: null,
                    backgroundColor: backgroundColor,
                    mini: true,
                    child: new Icon(icons[index], color: foregroundColor),
                    onPressed: () {},
                  ),
                  Text("Mehdi Bhai"),
                ],
              ),
            ),
          );
          return Positioned(
            bottom: (50.0 + 20.0) * (index + 1),
            child: child,
          );
        }).toList()
          ..add(
            new FloatingActionButton(
              heroTag: null,
              child: new AnimatedBuilder(
                animation: _controller,
                builder: (BuildContext context, Widget child) {
                  return new Transform(
                    transform: new Matrix4.rotationZ(
                        _controller.value * 0.5 * math.pi),
                    alignment: FractionalOffset.center,
                    child: new Icon(
                        _controller.isDismissed ? Icons.videocam : Icons.close),
                  );
                },
              ),
              onPressed: () {
                if (_controller.isDismissed) {
                  _controller.forward();
                } else {
                  _controller.reverse();
                }
              },
            ),
          ),
      ),
    );
  }
}
```

**Comment by mrmayurgithub** [comment]
> 
> 
> I ended up creating my own speed dial floating action button here is the code if you still need the functionality
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'dart:math' as math;
> 
> import 'package:flutter_speed_dial/flutter_speed_dial.dart';
> 
> void main() {
>   runApp(new MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return new MaterialApp(
>       home: new MyHomePage(),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   @override
>   State createState() => new MyHomePageState();
> }
> 
> class MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {
>   AnimationController _controller;
>   int _bottomNavIndex = 0;
> 
>   static const List<IconData> icons = const [
>     Icons.person,
>     Icons.person,
>     Icons.person,
>     Icons.person
>   ];
> 
>   @override
>   void initState() {
>     super.initState();
>     _controller = new AnimationController(
>       vsync: this,
>       duration: const Duration(milliseconds: 500),
>     );
>   }
> 
>   Widget build(BuildContext context) {
>     Color backgroundColor = Theme.of(context).cardColor;
>     Color foregroundColor = Theme.of(context).accentColor;
>     return new Scaffold(
>       backgroundColor: Colors.green[50],
>       appBar: new AppBar(title: new Text('Speed Dial Example')),
>       bottomNavigationBar: BottomAppBar(
>         shape: CircularNotchedRectangle(),
>         notchMargin: 8.0,
>         child: Container(
>           height: 60.0,
>         ),
>       ),
>       floatingActionButton: Stack(
>         overflow: Overflow.visible,
>         alignment: Alignment.center,
>         children: List<Widget>.generate(4, (int index) {
>           Widget child = new Container(
>             decoration: BoxDecoration(
>               shape: BoxShape.circle,
>             ),
>             alignment: FractionalOffset.topCenter,
>             child: new ScaleTransition(
>               scale: new CurvedAnimation(
>                 parent: _controller,
>                 curve: new Interval(0.0, 1.0 - index / icons.length / 2.0,
>                     curve: Curves.easeOut),
>               ),
>               child: Column(
>                 mainAxisAlignment: MainAxisAlignment.center,
>                 crossAxisAlignment: CrossAxisAlignment.center,
>                 children: [
>                   FloatingActionButton(
>                     heroTag: null,
>                     backgroundColor: backgroundColor,
>                     mini: true,
>                     child: new Icon(icons[index], color: foregroundColor),
>                     onPressed: () {},
>                   ),
>                   Text("Mehdi Bhai"),
>                 ],
>               ),
>             ),
>           );
>           return Positioned(
>             bottom: (50.0 + 20.0) * (index + 1),
>             child: child,
>           );
>         }).toList()
>           ..add(
>             new FloatingActionButton(
>               heroTag: null,
>               child: new AnimatedBuilder(
>                 animation: _controller,
>                 builder: (BuildContext context, Widget child) {
>                   return new Transform(
>                     transform: new Matrix4.rotationZ(
>                         _controller.value * 0.5 * math.pi),
>                     alignment: FractionalOffset.center,
>                     child: new Icon(
>                         _controller.isDismissed ? Icons.videocam : Icons.close),
>                   );
>                 },
>               ),
>               onPressed: () {
>                 if (_controller.isDismissed) {
>                   _controller.forward();
>                 } else {
>                   _controller.reverse();
>                 }
>               },
>             ),
>           ),
>       ),
>     );
>   }
> }
> ```

I tried using this code, but the onPressed property of sub FloatingActionButtons isn't working.

**Comment by perriguigui** [comment]
> 
> 
> > I ended up creating my own speed dial floating action button here is the code if you still need the functionality
> > ```dart
> > import 'package:flutter/material.dart';
> > import 'dart:math' as math;
> > 
> > import 'package:flutter_speed_dial/flutter_speed_dial.dart';
> > 
> > void main() {
> >   runApp(new MyApp());
> > }
> > 
> > class MyApp extends StatelessWidget {
> >   @override
> >   Widget build(BuildContext context) {
> >     return new MaterialApp(
> >       home: new MyHomePage(),
> >     );
> >   }
> > }
> > 
> > class MyHomePage extends StatefulWidget {
> >   @override
> >   State createState() => new MyHomePageState();
> > }
> > 
> > class MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {
> >   AnimationController _controller;
> >   int _bottomNavIndex = 0;
> > 
> >   static const List<IconData> icons = const [
> >     Icons.person,
> >     Icons.person,
> >     Icons.person,
> >     Icons.person
> >   ];
> > 
> >   @override
> >   void initState() {
> >     super.initState();
> >     _controller = new AnimationController(
> >       vsync: this,
> >       duration: const Duration(milliseconds: 500),
> >     );
> >   }
> > 
> >   Widget build(BuildContext context) {
> >     Color backgroundColor = Theme.of(context).cardColor;
> >     Color foregroundColor = Theme.of(context).accentColor;
> >     return new Scaffold(
> >       backgroundColor: Colors.green[50],
> >       appBar: new AppBar(title: new Text('Speed Dial Example')),
> >       bottomNavigationBar: BottomAppBar(
> >         shape: CircularNotchedRectangle(),
> >         notchMargin: 8.0,
> >         child: Container(
> >           height: 60.0,
> >         ),
> >       ),
> >       floatingActionButton: Stack(
> >         overflow: Overflow.visible,
> >         alignment: Alignment.center,
> >         children: List<Widget>.generate(4, (int index) {
> >           Widget child = new Container(
> >             decoration: BoxDecoration(
> >               shape: BoxShape.circle,
> >             ),
> >             alignment: FractionalOffset.topCenter,
> >             child: new ScaleTransition(
> >               scale: new CurvedAnimation(
> >                 parent: _controller,
> >                 curve: new Interval(0.0, 1.0 - index / icons.length / 2.0,
> >                     curve: Curves.easeOut),
> >               ),
> >               child: Column(
> >                 mainAxisAlignment: MainAxisAlignment.center,
> >                 crossAxisAlignment: CrossAxisAlignment.center,
> >                 children: [
> >                   FloatingActionButton(
> >                     heroTag: null,
> >                     backgroundColor: backgroundColor,
> >                     mini: true,
> >                     child: new Icon(icons[index], color: foregroundColor),
> >                     onPressed: () {},
> >                   ),
> >                   Text("Mehdi Bhai"),
> >                 ],
> >               ),
> >             ),
> >           );
> >           return Positioned(
> >             bottom: (50.0 + 20.0) * (index + 1),
> >             child: child,
> >           );
> >         }).toList()
> >           ..add(
> >             new FloatingActionButton(
> >               heroTag: null,
> >               child: new AnimatedBuilder(
> >                 animation: _controller,
> >                 builder: (BuildContext context, Widget child) {
> >                   return new Transform(
> >                     transform: new Matrix4.rotationZ(
> >                         _controller.value * 0.5 * math.pi),
> >                     alignment: FractionalOffset.center,
> >                     child: new Icon(
> >                         _controller.isDismissed ? Icons.videocam : Icons.close),
> >                   );
> >                 },
> >               ),
> >               onPressed: () {
> >                 if (_controller.isDismissed) {
> >                   _controller.forward();
> >                 } else {
> >                   _controller.reverse();
> >                 }
> >               },
> >             ),
> >           ),
> >       ),
> >     );
> >   }
> > }
> > ```
> 
> I tried using this code, but the onPressed property of sub FloatingActionButtons isn't working.
The problem comes from "Positioned" because you are going to move your fab (the graphic part) and on the other hand the click zone will not change and will remain in its initial position, under the main Fab.

**Comment by prateekmedia** [comment]
> > > I ended up creating my own speed dial floating action button here is the code if you still need the functionality
> > > ```dart
> > > import 'package:flutter/material.dart';
> > > import 'dart:math' as math;
> > > 
> > > import 'package:flutter_speed_dial/flutter_speed_dial.dart';
> > > 
> > > void main() {
> > >   runApp(new MyApp());
> > > ,,,
> > >   }
> > > }
> > > ```
> > 
> > 
> > I tried using this code, but the onPressed property of sub FloatingActionButtons isn't working.
> 
> The problem comes from "Positioned" because you are going to move your fab (the graphic part) and on the other hand the click zone will not change and will remain in its initial position, under the main Fab.

So What can be the solution for that?

**Comment by perriguigui** [comment]
Instead of using`Stack()` you can try to use a `Collum` like this:
```dart 
...
floatingActionButton: Column(
  crossAxisAlignment: CrossAxisAlignment.end,
  mainAxisAlignment: MainAxisAlignment.end,
  children: <Widget>[
      //your elements here
  ],
);
...
```
but you will probably have a problem with the animation.

**Comment by prateekmedia** [comment]
Checkout [new branch](https://github.com/darioielardi/flutter_speed_dial/tree/new), it has everything fixed.

**Comment by etegan** [comment]
Any status on this?
