### ISSUE TITLE
Overlay should be independent of closeManually

### ISSUE THREAD

**Issue by p0wl90** [darioielardi/flutter_speed_dial#78]
Hey!
I have a use case where the user can toggle the speed dial items on and off. Therefore, I set closeManually to true. The problem is that I still want the overlay to be shown. Also, I want users to be able to close by clicking somewhere outside the speed dial.
Would really appreciate this!

**Comment by prateekmedia** [comment]
Fixed in  16b6d4c please test it out if it works for you, also specify renderOverlay property

**Comment by p0wl90** [comment]
Thanks @prateekmedia, works great!
