### ISSUE TITLE
there are so many PR why not merge them?

### ISSUE THREAD

**Issue by jinfagang** [darioielardi/flutter_speed_dial#81]

**Comment by hpoul** [comment]
I'd assume due to 

https://github.com/darioielardi/flutter_speed_dial/commit/2ef2c44f22b3452b38352d80cbd133dcf3e30682#diff-04c6e90faac2675aa89e2176d2eec7d8R1

**Comment by jinfagang** [comment]
@darioielardi So the original author deperated it's maintainment, does anyone would start a new repo to continue development on this good lib?

I think it's worth to do it add more features on it.

**Comment by prateekmedia** [comment]
I have included many PR's + new features in my fork,
https://github.com/prateekmedia/flutter_speed_dial
