### ISSUE TITLE
Color Transparent not working

### ISSUE THREAD

**Issue by arfeenmushtaq** [darioielardi/flutter_speed_dial#85]
when i apply the color transparent, the buttons turn grey instead of adapting to the background-color

**Comment by avandame** [comment]
Don't know if this is helpful but I was able to make the SpeedDial transparent by making the elevation: 0.0 as well as making the backgoundColor: Colors.transparent

**Comment by prateekmedia** [comment]
You can try what @avandame said to make it completely transparent, closing it for now.
