### ISSUE TITLE
Custom Animated Icons

### ISSUE THREAD

**Issue by arfeenmushtaq** [darioielardi/flutter_speed_dial#86]
I need to use custom animated icons with speed dial
the most obvious one that starts with plus and ends with close icons

**Comment by walid-ashik** [comment]
You can achieve it by doing this. don't forget to remove this line
`//animatedIcon: AnimatedIcons.menu_close,
`
```
curve: Curves.bounceIn,
      animatedIconTheme: IconThemeData(size: 22.0),
      child: new IconTheme(
        data: new IconThemeData(color: Colors.white),
        child: new Icon(addButtonSelected ? Icons.clear : Icons.add),
      ),
      onOpen: () {
        setState(() {
          addButtonSelected = true;
        });
      },
      onClose: () {
        setState(() {
          addButtonSelected = false;
        });
      },
```

**Comment by prateekmedia** [comment]
Hey, you can checkout my fork, it already has this feature
https://github.com/prateekmedia/flutter_speed_dial

**Comment by prateekmedia** [comment]
Checkout V2 #90 it will be merged soon, you can use icon and activeIcon to Add icons to speed dial.
