### ISSUE TITLE
Hide when Navigating to different screen or navigation bar tab?

### ISSUE THREAD

**Issue by Velek** [darioielardi/flutter_speed_dial#87]
Using in an app that uses offstage widgets and bottom navigation.
I only want one tab to have the FAB.
Also need to hide the FAB when it navigates to subviews.

**Comment by prateekmedia** [comment]
Use can use the visibility property and check whether your current tab is your required tab then make speed dial visible or make it disappear. 

If you need more help then provide some demo code of yours to see the implementation in action.
