### ISSUE TITLE
onPress

### ISSUE THREAD

**Issue by Azhar-A** [darioielardi/flutter_speed_dial#89]
It's not working with onPress..
I have an issue that, I want a list of two icons, Sign out and edit profile, with edit profile I want a custom icon and don't wont to show the list in editing mode...

**Comment by prateekmedia** [comment]
If you use onPress then you will have to long press the dial to activate it, else you should use onOpen and onClose property of it to do your work, it is specified in the readme also that by using onPress, the dial will only open when long pressed.
