### ISSUE TITLE
SpeedDial could not be set key

### ISSUE THREAD

**Issue by monouni002** [darioielardi/flutter_speed_dial#96]

**Comment by prateekmedia** [comment]
Why do you need a key for speeddial? Any use cases?

**Comment by monouni002** [comment]
i need to have a key  for working with automate test 
and use key **findsOneWidget**

**Comment by prateekmedia** [comment]
Ok nice reason to use it, will add in sooner it is not difficult to add
this. ^_^

**Comment by monouni002** [comment]
^^ thank you very much
