### ISSUE TITLE
Can u make it useful for normal buttons?

### ISSUE THREAD

**Issue by AlbusSong** [darioielardi/flutter_speed_dial#98]
Up to now, only FloatingActionButton can embed this function. 
So why not make it universal for all buttons?

**Comment by prateekmedia** [comment]
Yes, it can be possible. But are their any use cases when this is useful, one such case I remember is to make it with draggable Flat buttons.

And also how will you specify which type of button to use if not Floatingactionbutton.

**Comment by nt4f04uNd** [comment]
i would like too see an api to make it work with any existing widget. like DialRoot or something

**Comment by AlbusSong** [comment]
> Yes, it can be possible. But are their any use cases when this is useful, one such case I remember is to make it with draggable Flat buttons #60.
> 
> And also how will you specify which type of button to use if not Floatingactionbutton.

To make it universal for all widget can be very useful actually.
Currently, why not just try to implement 1 or 2 fixed style for non-Floatingactionbuttons? Meanwhile leave all styles for Floatingactionbuttons unchanged. 

U don't need to make a perfect job in the beginning.
